### ISSUE TITLE
nn.ReverseTable

### ISSUE THREAD

**Issue by karthikncode** [Element-Research/rnn#10]
Hey Nicholas,
Thanks for adding in the BiSequencer. I see that code contains nn.ReverseTable() but I'm unable to find it in the nn or nnx packages. Am I missing something? I get the following error, of course:

    rnn/BiSequencer.lua:48: attempt to call field 'ReverseTable' (a nil value)

**Comment by nicholas-leonard** [comment]
Sudo luarocks install dpnn

**Comment by nicholas-leonard** [comment]
What I meant by that is that it was recently added to the dpnn package. You probably have an older version installed. You can update your dpnn package : 
```lua
sudo luarocks install dpnn
```
or if you installed locally
```lua
luarocks install --user dpnn
```

**Comment by karthikncode** [comment]
Works - thanks!
