### ISSUE TITLE
Multivariate time series prediction

### ISSUE THREAD

**Issue by rracinskij** [Element-Research/rnn#100]
Hi,

this is a further elaboration of issue #61 (time series prediction). There is an example of univariate time series prediction, but after some attempts to rewrite it into a multivariate version the issue looks quite tricky.

The problem is that the input should be not a sequence of values, but a sequence of vectors. E.g., inputs are air temperature, humidity and air pressure in t=0,-1,-2…-n and outputs are respective values (or some of them) in t=1. Is there any correct model setup within the current framework? Thank you.

**Comment by jfsantos** [comment]
You simply have to change your model output and criterion, e.g. using a `Linear` layer followed by a `Sigmoid` non-linearity and `MSECriterion`). There's nothing in RNN that enforces univariate prediction (in fact, even for classification problems, the output is multivariate is it is a vector of probabilities for each class).

**Comment by nicholas-leonard** [comment]
@ywelement is working on an example for multi-variate time-series prediction.

**Comment by rracinskij** [comment]
@jfsantos Yes, it's clear, but how should the input tensor look like? Using just a vector of values at each time step [Xt, Yt, ...], [Xt-1, Yt-1,...] works only in limited cases and I'm not sure that it is even theoretically correct.

**Comment by jfsantos** [comment]
Going from a tensor with (num_samples, num_timesteps, num_features) to a single vector (1, num_features) is what is often done so I do not see a big issue. The model is supposed to learn the relationships between the different variables in your data, so there should be no problem from having different types of variables in the same vector. Of course, the degree of success with such a model will depend on your data and whether short or long-term relationships are useful for modeling future data in the specific domain of your problem.

Could you explain what are the specific points that need to be clarified?

**Comment by rracinskij** [comment]
Next value Xt1 of univariate time series Xt, Xt-1 … Xt-n (X is scalar, I use capital letters just for visual convenience) can be predicted by using a seqLength tensor [Xt, Xt-1 .. Xt-n] as an input. It works actually well.

Same approach to multivariate time series would mean that input is a sequence of vectors [{Xt, Yt}, {Xt-1,Yt-1} … {Xt-n,Yt-n}] instead of scalars. So the input of the model should be modified somehow, for example by using a (1, numFeatures) tensor [Xt, Yt] as an input at every time step. It raises two questions:

1. is this approach feasible? Discussion in issue #92 states that it is, but my tests didn’t work well and it is unclear whether the cause is the input structure or other problem.

2. is there some better approach, as f. e. to construct an input tensor from both variables [Xt, Yt, Xt-1, Yt-1 … Xt-n, Yt-n]?

**Comment by ywelement** [comment]
@rracinskij A new example is put in rnn/examples/recurrent-time-series.lua to take multivariate time series. It uses the latest Sequencer (which internally uses backwardOnline). Does this help?

**Comment by rracinskij** [comment]
@ywelement Thanks a lot, it helps definitely. I'll test it with some synthetical data and provide feedback.
