### ISSUE TITLE
Canonical way to create tensors before targeting specific hardware?

### ISSUE THREAD

**Issue by hsheil** [Element-Research/rnn#104]
Hi @hughperkins, @nicholas-leonard 

Just a quick question on this code:

https://github.com/hughperkins/char-lstm/blob/debugging/train.lua#L168-L191

Is this now the canonical / preferred way to support CUDA and OpenCL (i.e. just work with FloatTensors and then either cuda() or cl() them as necessary)? I'll be getting onto this section of the code in #92 fairly soon and would like to support both in the preferred way..

Let me know, thanks!

**Comment by nicholas-leonard** [comment]
@hsheil You can use [nn.Convert()](https://github.com/Element-Research/dpnn#nn.Convert) to convert any input to cuda/cl automatically. This is the preferred way for me. But you could do it manually as in your linked example as well.

**Comment by hsheil** [comment]
@nicholas-leonard Ok cool thanks I'll check Convert() out!
