### ISSUE TITLE
Recurrence evaluation increases modelsize 

### ISSUE THREAD

**Issue by angelifrangite** [Element-Research/rnn#107]
Hey guys,

I noticed after performing:
1) one train iteration
2) set model:evaluate()
3) one evaluation iteration
4) set model:training()
while using a Recurrence with an rnn module (e.g. FastLSTM)
the modelsize increases and increases until the memory (GPU-RAM) is full.

The file is a small example demonstrating the issue.

Watching the GPU memory (Nvidia):
```terminal
watch nvidia-smi
```

So far I could reproduce it on three different computers.
Can anybody with a deeper knowledge of the recurrence modul tell me what I am doing wrong?

Thx guys

[test.txt](https://github.com/Element-Research/rnn/files/90657/test.txt)
```lua
require 'torch'
require 'cutorch'
require 'nn'
require 'cunn'
require 'rnn'


local tempm = 
        nn.Sequential()
        :add(nn.CSubTable())
        :add(nn.FastLSTM(1000,300,3))
        :add(nn.Linear(300,1000))
        :add(nn.Sigmoid())    

       
local model = nn.Sequencer(        
       		nn.Recurrence(tempm, 1000, 1, 3)
            )

local criterion = nn.SequencerCriterion(nn.BCECriterion())

model:cuda()
criterion:cuda()
model:zeroGradParameters()
model:training()



local inputs = { torch.rand(1000):cuda() , torch.rand(1000):cuda() , torch.rand(1000):cuda() }
local targets = { torch.rand(1000):cuda() , torch.rand(1000):cuda() , torch.rand(1000):cuda() }

for i=1, 100 do
	model:zeroGradParameters()
	print('Epoch '..i..' training:')
	for ii=1, 500 do
		local outputs = model:forward(inputs)
		err = criterion:forward(outputs, targets)
		local gradOutputs = criterion:backward(outputs, targets)
		model:backward(inputs, gradOutputs)
		model:updateParameters(0.001)
		model:zeroGradParameters()
	end

	print('Epoch '..i..' eval')
	model:forget()
	model:evaluate()
	for ii=1, 100 do	
		local outputs = model:forward(inputs)
		err = criterion:forward(outputs, targets)
	end
	model:forget()
	model:training()
end
```

**Comment by nicholas-leonard** [comment]
@angelifrangite The problem seems to be with evaluation. Looking into it.

**Comment by angelifrangite** [comment]
yes I think so too.

While debugging I noticed that just calling
```lua
model:evaluate()
model:training()
```
doesn't produce the problem.
Just the 
```lua
model:forward()
```
seems to set something internally that is not resetted by :training()

Sorry for not providing better information.

**Comment by nicholas-leonard** [comment]
@angelifrangite Just noticed that you are using a FastLSTM within your Recurrence. That is really non-standard, or at least it is a use-case we have yet to unit test. So I think the issue has something to do with the fact the `forget()` isn't being propagated to FastLSTM. Let me build this into a unit test and find a fix.

**Comment by nicholas-leonard** [comment]
@angelifrangite This https://github.com/Element-Research/rnn/commit/48d1cdd3482980abdfc6f1c53bebaba5608f504f fixes it . Thanks for letting us know!

**Comment by angelifrangite** [comment]
Holy...that was fast. It works perfect now! 

Thank you **very** much.
