### ISSUE TITLE
Recurrence with ParallelTable not calculable

### ISSUE THREAD

**Issue by angelifrangite** [Element-Research/rnn#109]
Hey,

using this example https://github.com/Element-Research/rnn#recurrence (a bit modified) does not work.
The error occurs during the model:backward call.
I think paralleltable picks the wrong table-dimension?

```lua
require 'nn'
require 'rnn'

local inputs, targets = {}, {}
for i=1, 3 do
	table.insert(inputs, torch.rand(10))
	table.insert(targets, torch.rand(5))
end

local criterion = nn.SequencerCriterion(nn.BCECriterion())

local rm = nn.Sequential()
   :add(nn.ParallelTable()
      :add(nn.Linear(10, 7))
      :add(nn.Linear(5, 7)))
   :add(nn.CAddTable())
   :add(nn.Linear(7,5))
   :add(nn.Sigmoid())

local model = nn.Sequencer(
      nn.Recurrence(rm, 5, 1)
)

print(model)
	
local outputs = model:forward(inputs)
local loss = criterion:forward(outputs, targets)
local gradOutputs = criterion:backward(outputs, targets)

model:backward(inputs, gradOutputs)
```

error:
```terminal
/home/user/torch/install/share/lua/5.1/nn/Linear.lua:80: attempt to index local 'input' (a number value)
```

**Comment by angelifrangite** [comment]
So I am no programmer so please bear with me:
I tried to debug this problem and think the error occurs in:
[Recurrence.lua](https://github.com/Element-Research/rnn/blob/master/Recurrence.lua) Line 155
 
```lua
recurrentModule:accGradParameters({step, output}, gradOutput, scale)
```
I can't wrap my head around the reason step is forwarded.
Is it possible that:
```lua
recurrentModule:accGradParameters({input, output}, gradOutput, scale)
```
should be done instead?

Thanks for taking your time

**Comment by nicholas-leonard** [comment]
@angelifrangite My bad. Fixed by https://github.com/Element-Research/rnn/commit/86ca24546a23d61c43c2d1a576e38a18b78c1ede . Thanks @angelifrangite !
