### ISSUE TITLE
AbstractRecurrent forget() execute unwanted assertion?

### ISSUE THREAD

**Issue by zhengwy888** [Element-Research/rnn#11]
in this section of the code
https://github.com/Element-Research/rnn/blob/master/AbstractRecurrent.lua#L113

```
function AbstractRecurrent:forget(offset)
   offset = offset or 0
   if self.train ~= false then
      -- bring all states back to the start of the sequence buffers
      local lastStep = self.step - 1
      
      if lastStep > self.rho + offset then
         local i = 1 + offset
```

forget() is trying to check the boolean value self.train, but since AbstractRecurrent's parent class is nn.Container, there is no self.train, so the code below end up executing whether you called training() or evaluate().

**Comment by nicholas-leonard** [comment]
That functionality was recently added to nn : https://github.com/torch/nn/pull/290 . 
You can update your nn package : 
```lua
sudo luarocks install nn
```
or if you installed locally
```lua
luarocks install --user nn
```
