### ISSUE TITLE
problems in sharing lstms' weight

### ISSUE THREAD

**Issue by liangjz92** [Element-Research/rnn#114]
a = nn.LSTM(...)
b = a:clone('weight','bias'...)    --not working now, because the clone function can't touch recurrentModule
b = nn.LSTM(....)
b = share(a,'weight')  -- also not working, the same reason 
I think LSTM(FastLSTM) should overwrite share() and clone() function

**Comment by nicholas-leonard** [comment]
@liangjz92 have you tried [sharedClone](https://github.com/Element-Research/dpnn)?

**Comment by liangjz92** [comment]
@nicholas-leonard 
My mistake, I called share function before :cuda(). so it actually act in a unshare way, the rnn package is right. just wasted a lot of time ...
