### ISSUE TITLE
serialize a big model

### ISSUE THREAD

**Issue by lifengjin** [Element-Research/rnn#115]
Hi, 
I am trying to serialize a big bilayered LSTM model and constantly run into out of memory problem from Luajit. (The potential problem may have something to do with that 2G memory limit from Luajit.) I have been trying to make this work for a few days. My model is a Sequencer(LSTM) and the inputs are of various lengths. Is it true that the model grows in size with regard to the length of the input, despite calling forget() after each input? In other words, does forget() compress the Sequencer with tons of clones back to just one module with parameters? Is there a proper way to serialize a model like this?

**Comment by lifengjin** [comment]
I guess one potential thing is to use nn.Serial() to control what's serialized. Looking into this...

**Comment by nicholas-leonard** [comment]
@lifengjin I have been running into the same issue for training the [char-lsm](https://github.com/hughperkins/char-lstm) with long sequences. The only way I found to solve it was to uninstall luajit/torch and reinstall it with lua5.2 support. See https://github.com/torch/distro for instructions on how to do this.
