### ISSUE TITLE
Recurrent Model of Visual Attention + optim sgd

### ISSUE THREAD

**Issue by pefi9** [Element-Research/rnn#119]
Hi,
I'm trying to train the "Recurrent Model of Visual Attention" with sgd from optim package. But I have difficulties to train the network with pre-defined parameters and one epoch take much longer than in the original script. Is there anything I have to change going from dp.experiment to optim.sgd on the model or in training process?

**Comment by nicholas-leonard** [comment]
@pefi9 Can you open-source your script in a github repository? We can check it out together.

**Comment by pefi9** [comment]
@nicholas-leonard Thanks. The code: https://github.com/pefi9/visual_attention_optim
I tried both training methods. One is, let's say, custom "train()" and second use optim package "trainOptin()".

**Comment by nicholas-leonard** [comment]
https://github.com/pefi9/visual_attention_optim/issues/1

**Comment by pefi9** [comment]
Thanks, that helped.
