### ISSUE TITLE
Handling variable length sequences?

### ISSUE THREAD

**Issue by hsheil** [Element-Research/rnn#121]
Hi, below is some sample input + target data into an LSTM, along with the runtime error this data causes below.

If I standardise the number of events in each session and / or use a batchSize of 1, then no error is thrown and training continues as normal.

Is it a restriction of the framework that I need to standardise the inputs and they can't vary by length or is there more likely to be a flaw in my code? I'm aware of MaskZero - is that a potential solution to this problem? I'm happy to standardise the inputs - The reason I took this "as-is" approach first is I'm interested in measuring what training improvement if any is provided by "telling" the network about periods of user inactivity between each event via blank / no-op events vs stripping out that information and only providing the real user events. Thanks in advance!

    34154697 events, 33003944 clicks, 1150753 buys, 9758065 sessions  
    52739 unique items, min itemId 214507224, maxItemId 1178837797  
    19949 unique items purchased  
    339 unique cats 
    Data loaded in 76.243667125702 secs 
    Training phase starting 
    epoch 1 
    Input table:
    {
      1 : CudaTensor - size: 4x187
      2 : CudaTensor - size: 6x187
      3 : CudaTensor - size: 3x187
      4 : CudaTensor - size: 2x187
      5 : CudaTensor - size: 2x187
    }
    Target table:
    {
      1 : CudaTensor - size: 4
      2 : CudaTensor - size: 6
      3 : CudaTensor - size: 3
      4 : CudaTensor - size: 2
      5 : CudaTensor - size: 2
    }

Runtime error:

    /home/hsheil/torch/install/bin/luajit: /home/hsheil/torch/install/share/lua/5.1/nn/CAddTable.lua:12: bad argument #2 to 'add' (sizes do not match at /tmp/luarocks_cutorch-scm-1-7482/cutorch/lib/THC/THCTensorMathPointwise.cu:113)
    stack traceback:
      [C]: in function 'add'
      /home/hsheil/torch/install/share/lua/5.1/nn/CAddTable.lua:12: in function 'updateOutput'
      /home/hsheil/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'updateOutput'
      /home/hsheil/torch/install/share/lua/5.1/nn/ConcatTable.lua:11: in function 'updateOutput'
      /home/hsheil/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'updateOutput'
      /home/hsheil/torch/install/share/lua/5.1/nn/ConcatTable.lua:11: in function 'updateOutput'
      /home/hsheil/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'updateOutput'
      /home/hsheil/torch/install/share/lua/5.1/nn/ConcatTable.lua:11: in function 'updateOutput'
      /home/hsheil/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'updateOutput'
      /home/hsheil/torch/install/share/lua/5.1/rnn/LSTM.lua:162: in function 'updateOutput'
      /home/hsheil/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'updateOutput'
      /home/hsheil/torch/install/share/lua/5.1/rnn/Recursor.lua:24: in function 'updateOutput'
      /home/hsheil/torch/install/share/lua/5.1/rnn/Sequencer.lua:47: in function 'forward'
      example_part1.lua:109: in main chunk
      [C]: in function 'dofile'
      ...heil/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
      [C]: at 0x00406670

**Comment by hsheil** [comment]
Just as a quick update on this issue - the way I'm handling it for now is to put sequences of the same length in the same batch i.e. "like with like" - I can vary the sequence length with no problems between batches, just not *within* batches. It remains to be seen what positive or negative impact this has on training - one of my TODOs is to implement curriculum learning so I need to do this anyway. For the YOOCHOOSE data set, here is the session coverage by sequence length - a batch contains multiple sessions (currently 128):

# events	# sessions	percentage
1	1,490,817	15.28%
2	3,689,445	53.09%
3	1,673,841	70.24%
4	974,337	80.23%
5	559,499	85.96%
6	376,432	89.82%
7	242,302	92.30%
8	173,652	94.08%
9	121,928	95.33%
10	92,485	96.28%
11	67,047	96.96%
12	53,653	97.51%
13	40,597	97.93%
14	32,746	98.27%
15	25,868	98.53%
16	21,033	98.75%
17	17,052	98.92%
18	14,292	99.07%

**Comment by nicholas-leonard** [comment]
@hsheil I just want to make sure that you understand that the length of the input table is the length of the sequence. Each element of that table represents a time-step. Each element is thus a tensor where the first dimension is of size batchSize. So to be clear, the elements of the table are not sequences, but time-steps of the sequence.

**Comment by hsheil** [comment]
@nicholas-leonard No, I didn't understand that, thanks for the clarification! Refactoring the code now to measure the improvement - it's already training reasonably well - testimony to the resilience of RNNs / LSTM even when presented with bad data I guess, e.g.

    Start:
    epoch loss  0.72984601855278 batch loss 0.72984601855278    
    epoch loss  0.73019070923328 batch loss 0.73053539991379    
    epoch loss  0.73602413535118 batch loss 0.74769098758698
    <snip />
    After 105 mins of training:
    epoch loss  0.14304796027273 batch loss 0.0031834277382586  
    epoch loss  0.14304637035609 batch loss 0.0032767984899692  
    epoch loss  0.14304477894482 batch loss 0.0031422231084434

**Comment by hsheil** [comment]
Just updating this issue for posterity - significantly better training results observed after shorter training time (11 mins vs 105 mins) using the correct method of unpacking, repacking and presenting data to the LSTM network. Never under-estimate the power of presenting the right data to a model!:

	eloss 	0.048482530867631	 bloss 	0.010092716367217	0.067359924316406	 secs	
	eloss 	0.048478649725846	 bloss 	0.0097797849863127	0.065828084945679	 secs	
	eloss 	0.048474784740022	 bloss 	0.0099331461024121	0.066329956054688	 secs

**Comment by nicholas-leonard** [comment]
@hsheil Nice!

**Comment by jinghuangzhu** [comment]
@hsheil I have same data format as yours, i.e. the input are variable length sequences (each sequence is a vector). I did not get how you solved this problem eventually --- how to unpack, repack and give the data to the LSTM network. Can you please give an example? Thanks.

**Comment by nicholas-leonard** [comment]
@jinghuangzhu Checkout the noise-contrastive-estimate.lua example for a concrete variable length sequence use-case. It uses nn.MaskZero and dataload.MultiSequence

**Comment by hsheil** [comment]
Hi @jinghuangzhu 

Yep check out the code pointed to by @nicholas-leonard. If you want to additionally examine my code, check out build_network() in main.lua to see how I configured the model to use MaskZero - don't forget to wrap your criterion as well (e.g. lines 49 - 51).

RE: data massaging / construction, check out getNextSession() in data.lua. Remember when padding that the MaskZero impl wants empty vectors at the *start* of each table, not the end - cf. lines 533 - 538: "Warning: padding must come before any real data in the input sequence -- (padding after the real data is not supported and will yield unpredictable results without failing)."

**Comment by jinghuangzhu** [comment]
@hsheil Sorry, I just realized I don't know where is your code :). Thanks for the pointers.

**Comment by nicholas-leonard** [comment]
1. MultiSequence can handle that. I just added a small unit test to dataload to make sure.

2. You don't need to put the padding in front of the input anymore. MultiSequence + MaskZero + RNN will handle everything just file.

The input to the RNN/LSTM/GRU must be of shape : seqlen x batchsize x inputsize. This is what MultiSequence provides.
