### ISSUE TITLE
AbstractRecurrent.lua:45: attempt to call method '_updateGradInput' (a nil value)

### ISSUE THREAD

**Issue by mansirankawat** [Element-Research/rnn#122]
Hi,
I am getting an error when I use RNN library for LSTM:

AbstractRecurrent.lua:45: attempt to call method '_updateGradInput' (a nil value)
stack traceback:
	...ps/torch/install/share/lua/5.1/rnn/AbstractRecurrent.lua:45: in function 'updateGradInput'
	torch/install/share/lua/5.1/rnn/Sequencer.lua:78: in function 'updateGradInput'
	torch/install/share/lua/5.1/nn/Sequential.lua:55: in function 'updateGradInput'
	torch/install/share/lua/5.1/nn/Parallel.lua:53: in function 'updateGradInput'
	SpatialLSTM.lua:163: in function 'opfunc'
	torch/install/share/lua/5.1/optim/rmsprop.lua:32: in function 'rmsprop'
	SpatialLSTM.lua:181: in function 'main'
	SpatialLSTM.lua:226: in main chunk
	[C]: in function 'dofile'
	torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670

**Comment by nicholas-leonard** [comment]
@mansirankawat Where did you find this SpatialLSTM? It hasn't been updated to work with the latest version of the rnn package.

**Comment by mansirankawat** [comment]
@nicholas-leonard  I am using ConvLSTM by Viorik as listed on the doc

**Comment by nicholas-leonard** [comment]
@mansirankawat Ok I am working on a Pull Request for that repo.

**Comment by mansirankawat** [comment]
Okay thanks! Any idea how long would it take for that to be updated?

**Comment by nicholas-leonard** [comment]
@mansirankawat @viorik I did as much as I have time to do here : https://github.com/viorik/ConvLSTM/pull/2 . But I don't have time to debug the rest, sorry.

**Comment by mansirankawat** [comment]
Okay thanks so much!

**Comment by mansirankawat** [comment]
@nicholas-leonard Is it possible to use the previous version of RNN until the ConvLSTM is updated to a newer version?

**Comment by nicholas-leonard** [comment]
Yes it has changed.

**Comment by nicholas-leonard** [comment]
I think this was fixed by @viorik
