### ISSUE TITLE
Cell/Hidden State with MaskZero and Sequences of Different Lengths

### ISSUE THREAD

**Issue by ankush-me** [Element-Research/rnn#123]
I have a question regarding the cell/hidden state values when processing sequences of different lengths:

Say you have created a batch of sequences of different lengths by padding the shorter sequences with **zeros at the beginning**, and you use `nn.Sequencer(nn.MaskZero(nn.LSTM(10,10),1))` to create the RNN. Then I think, the **initial** cell (and hidden) values for shorter sequences would not be the equal to the **initial** cell (and hidden) values for a sequence which has length = max_sequence_length. Is this correct? If yes, isn't this a problem?

**Comment by nicholas-leonard** [comment]
@ankush-me You should do this instead : `local seq = nn.Sequencer(nn.LSTM(10,10):maskZero(1))`. Please `luarocks install rnn` as I updated the MaskZero to issue a warning when it is used that way : #127 . I also added a unit test to make sure it does as you say. Thanks :)

**Comment by ankush-me** [comment]
Thank you @nicholas-leonard!
