### ISSUE TITLE
Using combine_all_parameters

### ISSUE THREAD

**Issue by rahulk90** [Element-Research/rnn#124]
I'm building a model that has several sub-models within it, each built with the rnn library. 

After a forward/backward step, I would like to use optim to train all the parameters at one go. 

To do this, I'm using the following function to combine the parameters of each of the different sub-models. 
https://github.com/oxford-cs-ml-2015/practical6/blob/master/model_utils.lua

Here is a small example:
```
require 'rnn'
m_utils = require 'model_utils.lua'

mlp1 = nn.Sequencer()(nn.Recursor(nn.LSTM(100,100), 10))
mlp2 = nn.Sequencer()(nn.Recursor(nn.LSTM(200,200), 10))

w,dw = m_utils.combine_all_parameters(mlp1,mlp2)

--Do forward/backward on mlp1,mlp2
--Update w using dw with optim
```
Is there anything to watch out for in terms of how the internal shared clones are handled within the rnn package? 

Alternatively, is there another way to do this?

**Comment by nicholas-leonard** [comment]
@rahulk90 You can do this with a little hack : 
```lua
cont = nn.Container():add(mlp1):add(mlp2)
w,dw = cont:getParameters()
```

Other than that, rnn uses dpnn which overwrites the getParameters to be fully recursive such that it works with rnn modules : https://github.com/Element-Research/dpnn/blob/master/Module.lua#L182 .

**Comment by rahulk90** [comment]
@nicholas-leonard Thanks! Thats useful to know. I'll use that.

Finally, if i've defined the following:
```
require 'rnn'
lstm  = nn.LSTM(100,100)
mlp1 = nn.Sequencer()(nn.Recursor(lstm, 10))
mlp2 = nn.Sequencer()(nn.Recursor(nn.LSTM(200,200), 10))
```
I assume it doesnt matter if i add `lstm` or the wrapping Sequencer module `mlp1` into the container when I get the parameters?

**Comment by nicholas-leonard** [comment]
@rahulk90 Nope doesn't matter. But make sure you include both LSTMs. More generally, include all modules with parameters into the container before calling getParameters.

**Comment by rahulk90** [comment]
Perfect. Thanks @nicholas-leonard! Closing this.
