### ISSUE TITLE
No value in hidden state and output variables

### ISSUE THREAD

**Issue by kvitajakub** [Element-Research/rnn#126]
Hello,

I was playing with the `cell` and `output` variables and I have no values in them. For example, code from  issue #112 

```lua
require 'rnn'
di,dh,dout,T = 10,100,20,3
fastNN1 = nn.FastLSTM(dh,dh)
fastNN2 = nn.FastLSTM(dh,dh)
local rn = nn.Sequential()
  rn:add(nn.Linear(di, dh))
  rn:add(fastNN1)
  rn:add(fastNN2)
  rn:add(nn.Linear(dh, dout))
rn = nn.Sequencer(nn.Recursor(rn, T))
--Assume A,B,C correctly defined
local inputs = {torch.randn(3,di), torch.randn(3,di), torch.randn(3,di)}

O1 = rn:forward(inputs) --F1
O2 = rn:forward(inputs) --F2

-- print(O2[1]:sum(), O2[2]:sum(), O2[3]:sum())

rn:zeroGradParameters()
rn:forget()

O1 = rn:forward(inputs) --F1
local output1, cell1 = fastNN1.output, fastNN1.cell
local output2, cell2 = fastNN2.output, fastNN2.cell

print(output1)
print(cell1)
```
will produce:
```
[torch.DoubleTensor with no dimension]

nil	
```
I tried to put `rn:remember('both')` there too, but with no effect. `cells` and `outputs` are empty, too.  Am I doing something wrong?

**Comment by rahulk90** [comment]
Are you running this on the torch interpreter? If so, the local variables won't be accessible. 

I ran the above as a torch script instead and got two 3x100 tensors printed.

**Comment by kvitajakub** [comment]
I ran it as a script and had the problem.
However, I updated the rnn package and finally I am getting the tensors.
Thanks for the help, I will close the issue now.
