### ISSUE TITLE
Strange bug if using MaskZeroCriterion and SequencerCriterion together

### ISSUE THREAD

**Issue by puuzll** [Element-Research/rnn#128]
It do not work if using MaskZeroCriterion() and SequencerCriterion() together:
```lua
function rnntest.SequencerCriterion()
   local batchSize = 4
   local inputSize = 10
   local outputSize = 7
   local nStep = 5  
   local criterion = nn.MaskZeroCriterion(nn.ClassNLLCriterion(),1)
   local sc = nn.SequencerCriterion(criterion:clone())
   local input = {}
   local target = {}
   local err2 = 0
   local gradInput2 = {}
   for i=1,nStep do
      input[i] = torch.randn(batchSize, inputSize)
      target[i] = torch.randperm(inputSize):narrow(1,1,batchSize)
      err2 = err2 + criterion:forward(input[i], target[i])
      gradInput2[i] = criterion:backward(input[i], target[i]):clone()
   end
   local err = sc:forward(input, target)
   mytester:asserteq(err, err2, 0.000001, "SequencerCriterion forward err") 
   local gradInput = sc:backward(input, target)
   for i=1,nStep do
      mytester:assertTensorEq(gradInput[i], gradInput2[i], 0.000001, "SequencerCriterion backward err "..i)
   end
   mytester:assert(sc.isStateless, "SequencerCriterion stateless error")
end
```
this test function will failed with
```
--------------------------------------------------------------------------------	
SequencerCriterion
SequencerCriterion backward err 1
 TensorEQ(==) violation   val=0.25, condition=1e-06
	...n/NLP/Torch/torch/install/share/lua/5.1/torch/Tester.lua:61: in function 'assertTensorEq'
	rnntest.lua:31: in function <rnntest.lua:10>
	
--------------------------------------------------------------------------------	
SequencerCriterion
SequencerCriterion backward err 2
 TensorEQ(==) violation   val=0.25, condition=1e-06
	...n/NLP/Torch/torch/install/share/lua/5.1/torch/Tester.lua:61: in function 'assertTensorEq'
	rnntest.lua:31: in function <rnntest.lua:10>
	
--------------------------------------------------------------------------------	
SequencerCriterion
SequencerCriterion backward err 3
 TensorEQ(==) violation   val=0.25, condition=1e-06
	...n/NLP/Torch/torch/install/share/lua/5.1/torch/Tester.lua:61: in function 'assertTensorEq'
	rnntest.lua:31: in function <rnntest.lua:10>
	
--------------------------------------------------------------------------------	
SequencerCriterion
SequencerCriterion backward err 4
 TensorEQ(==) violation   val=0.25, condition=1e-06
	...n/NLP/Torch/torch/install/share/lua/5.1/torch/Tester.lua:61: in function 'assertTensorEq'
	rnntest.lua:31: in function <rnntest.lua:10>
	
--------------------------------------------------------------------------------	
```
This test fuction is indentical with the one in 'rnn/test.lua' except this line 
```lua
local criterion = nn.MaskZeroCriterion(nn.ClassNLLCriterion(),1)
```
Does any one post this before?
It is seemed that MaskZeroCriterion is an stateful criterion, can anybody tell me why?

**Comment by mzhai2** [comment]
I am having the same problem with MaskZeroCriterion training a LM.

**Comment by puuzll** [comment]
@mzhai2 ,instead of  using ```SequencerCriterion ```, you can apply ```MaskZeroCriterion``` to an sequence by youself :
```lua
local nll = nn.ClassNLLCriterion()
local mznll = nn.MaskZeroCriterion(nll, 1)
gradInput = {}
for i = 1,timeStep do
    err =  mznll :forward(output[i],target[i])
    gradInput[i]  = mznll :backward(output[i],target[i]):clone()
end
```
notice that ```clone()```is needed.

**Comment by nicholas-leonard** [comment]
@puuzll Update the rnn package : `luarocks install rnn`. The SequencerCriterion and RepeaterCriterion have been modified to handle the wrapping of stateful criterions. Thanks for the bug report :)

**Comment by mzhai2** [comment]
I updated but I am still getting an error when I add use a mask.
`criterion = nn.SequencerCriterion(nn.MaskZeroCriterion(nn.ClassNLLCriterion(),1))
`
vs`
criterion = nn.SequencerCriterion(nn.ClassNLLCriterion())
`
`
/Users/Mike/torch/install/bin/luajit: ...ke/torch/install/share/lua/5.1/rnn/MaskZeroCriterion.lua:35: bad argument #1 to 'index' (sizes do not match at /tmp/luarocks_cutorch-scm-1-186/cutorch/lib/THC/generic/THCTensorCopy.c:47)
stack traceback:
	[C]: in function 'index'
	...ke/torch/install/share/lua/5.1/rnn/MaskZeroCriterion.lua:35: in function 'recursiveMask'
	...ke/torch/install/share/lua/5.1/rnn/MaskZeroCriterion.lua:75: in function 'forward'
	...e/torch/install/share/lua/5.1/rnn/SequencerCriterion.lua:39: in function 'forward'
	./train.lua:106: in function 'opfunc'
	/Users/Mike/torch/install/share/lua/5.1/optim/adagrad.lua:30: in function 'optimMethod'
	./train.lua:126: in function 'train'
	main.lua:96: in main chunk
	[C]: in function 'dofile'
	...Mike/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x010eea6bd0
`

**Comment by mzhai2** [comment]
@puuzll Don't I need to iterate backwards in timesteps for mznll:backward?

**Comment by nicholas-leonard** [comment]
@mzhai2 What code are you running to get that error? so I can reproduce on my end.

**Comment by Tushar-N** [comment]
Hi, 
I'm facing a similar issue. The problem occurs when the input to the criterion is all zeros (i.e. all the inputs are masked, say from an output of a masked module) Here's a snippet of code that triggers it:

```lua
local input, target=torch.rand(3,2), torch.Tensor({1,2,1}) -- batch size 3, 2 classes
local crit=nn.MaskZeroCriterion(nn.ClassNLLCriterion(), 1)
print (crit:forward(input, target)) -- no problem here, prints something 

inp:fill(0) -- output from a masked module gives me all zeros
print (crit:forward(input, target))
```

> 
> ...ll/torch/install/share/lua/5.1/rnn/MaskZeroCriterion.lua:35: bad argument #2 to 'index' (Index is supposed to be a vector at /home/mall/torch/pkg/torch/lib/TH/generic/THTensorMath.c:130)
> stack traceback:
> 	[C]: in function 'index'
> 	...ll/torch/install/share/lua/5.1/rnn/MaskZeroCriterion.lua:35: in function 'recursiveMask'
> 	...ll/torch/install/share/lua/5.1/rnn/MaskZeroCriterion.lua:75: in function 'forward'
> 	[string "_RESULT={crit:forward(inp, target)}"]:1: in main chunk
> 	[C]: in function 'xpcall'
> 	/home/mall/torch/install/share/lua/5.1/trepl/init.lua:651: in function 'repl'
> 	...mall/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:199: in main chunk
> 	[C]: at 0x00406670	
>                                                                       [0.0001s]

**Comment by nicholas-leonard** [comment]
@Tushar-N https://github.com/Element-Research/rnn/commit/4c4895a2da501ac2b6c66eec4d174ca12c3f5a1d should fix it.

**Comment by Tushar-N** [comment]
Thanks!
