### ISSUE TITLE
MaskZero clears the output when a zero vector occurs in the middle of sequence

### ISSUE THREAD

**Issue by iamalbert** [Element-Research/rnn#136]
Not sure if I misunderstanding this: MaskZero makes it possible to process sequences of different lengths in a batch, by means of padding zero vectors in the beginning of sequences that are shorter than the longest one.

```lua
m = nn.Sequencer( nn.LSTM( inputDim, outputDim ):maskZero(1) )
```

But if there exists a zero vector after the first nonzero vector, say, an OOV in the middle of a sentence, MaskZero will still zeros the output at that position, which means the output and afterward ones are all wrong.

If MaskZero is introduced only for dealing with sequences of different lengths, maybe it should be implemented on `Sequencer`, not `AbstractRecurrent`?

**Comment by nicholas-leonard** [comment]
@iamalbert I understand your use-case and the possibility of the glitch that can be introduced. However, OOV should be non-zero in 99.9999% of cases as its embedding should still hold meaning (non-zeros). 

The advantage of introducing `MaskZero` at the level of `AbstractRecurrent` is that it can easily zero the hidden states as well (like LSTM cells). However, it would still be possible to handle zero masking at the level of the Sequencer by introducing a `Module:mask` method of sorts... In any case, I think it works well as it is.
