### ISSUE TITLE
[Question] Merging vs summing bidirectional components

### ISSUE THREAD

**Issue by kmnns** [Element-Research/rnn#141]
Hi, I am curious about the details of the `BiSequencer` (BRNN).

Most of the current papers (that I know) use a variant of BRNNs where the outputs of the forward and back components are **summed** to form the common layer output. These papers usually refer back to the winning implementation in the original paper by Schuster 1997 (http://www.di.ufpe.br/~fnj/RNA/bibliografia/BRNN.pdf).

The other (inferior) variant these guys tried (called "MERGE") treated the forward/backward components as two independent "experts" and **concatenated** their outputs. In case of a single-level network, this effectively results in two separate networks.

`BiSequencer` seems to implement the inferior variant by default. The two "experts" are **concatenated** by `nn.JoinTable`, which in turn can be fed into deeper levels.

Am I wrong? Is there a specific reason you are not summing up the forward/backward components by default? (I guess via `nn.CAddTable`?).

This struck me as a gotcha, because suddenly I got twice the vector size in the second-level input and didn't realize it until later. I first assumed that the `BiSequencer` just does what all the cool kids seem to do.

**Comment by quilby** [comment]
Since "Learning to Align and Translate" all the cool kids are concatenating, not summing. If you have seen any papers in the last year or two that sum instead of concat, please post them here.

**Comment by kmnns** [comment]
There was a misunderstand about where the weighting takes place. Turns out that without my false assumption, concatenation of the two components and subsequent weighting is equivalent to individual weighting and then summation. Sorry about that. Case closed.
