### ISSUE TITLE
Some thoughts about the doc when manually do fwd/bwd pass

### ISSUE THREAD

**Issue by blackyang** [Element-Research/rnn#143]
Hi,

First thanks for your great package!

There is a piece of code in the doc:

```
rnn = nn.LSTM(10, 10) -- AbstractRecurrent instance
local outputs = {}
for i=1,nStep do -- forward propagate sequence
   outputs[i] = rnn:forward(inputs[i])
end

for i=nStep,1,-1 do -- backward propagate sequence in reverse order
   gradInputs[i] = rnn:backward(inputs[i], gradOutputs[i])
end

rnn:forget()
```

I am doing some stuff related to attention model, so I need to manually do the fwd/bwd pass like the code above. It took me some time to find a bug in my implementation, that is, for a non-recurrent module, we need to explicitly clone the forward outputs. For rnn module we are good.

The correct code should be like:
```
local outputs = {}
for i=1,nStep do -- forward propagate sequence
   tmp = rnn:forward(inputs[i])
   outputs[i] = model:forward(tmp):clone()
end
```

I think it would be great if we can add some comments in doc to mention this.

**Comment by nicholas-leonard** [comment]
@blackyang Not sure where to add it. You can submit a PR if you see a place to put it in.

Otherwise, instead of cloning the output of model, wrap it in a nn.Recursor instance as it will do the cloning for you.

**Comment by blackyang** [comment]
@nicholas-leonard  thanks for your reply! 

Can we decorate a nngraph with a nn.Recursor? Because my model would be a nngraph in the following code:

```
local outputs = {}
for i=1,nStep do -- forward propagate sequence
   outputs[i] = model:forward({{input_i}, {output_i-1}})
end
```

So I guess it might be better not wrapping it in a nn.Recursor

**Comment by nicholas-leonard** [comment]
@blackyang Wrap your nngraph into a nn.gModule, which you can then wrap into a nn.Recursor.

**Comment by blackyang** [comment]
Thanks! That would make my code cleaner
