### ISSUE TITLE
More clear sentiment analysis example?

### ISSUE THREAD

**Issue by coodoo** [Element-Research/rnn#148]
I had been trying to figure out how to implement sentiment analysis by following [sequence to one](https://github.com/Element-Research/rnn/blob/master/examples/sequence-to-one.lua) example but found it rather hard to understand.

Just wondering is there any more detailed examples using real world datasets like `imdb` or `twitter` to showcase the true power of `rnn`? Thanks.

**Comment by nicholas-leonard** [comment]
@coodoo It is on my To Do list to include the twitter dataset. Just to be clear, you mean the one referred to on this page right : http://help.sentiment140.com/for-students/ ?

**Comment by Sandy4321** [comment]
yes you may start from this link
http://cs.stanford.edu/people/alecmgo/trainingandtestdata.zip

though it is not true data since
it was labeled by emotions
but code development it is ok
however
for model tuning to be  get useful model
it is faked data
by the way for me better to have only python based code
since torch gives up to python
do you know python code example for rnn/last/gru
except
https://github.com/fchollet/keras/blob/master/examples/imdb_lstm.py

http://deeplearning.net/tutorial/lstm.html

https://github.com/mesnilgr/is13

https://github.com/umass-semeval/semeval16
http://k8si.github.io/2016/01/28/lstm-networks-for-sentiment-analysis-on-tweets.html


you will find more data here
semeval16-master\data\

**Comment by coodoo** [comment]
@nicholas-leonard Yes, that's the original source, later on there's a couple of variations based on that, including examples from `keras` as mentioned above.

I was basically following [kaggle's sunny side up](https://github.com/Lab41/sunny-side-up) example which provides both `IMDB` and `twitter` datasets, might be a useful reference.

But really any example that walks the reader from end to end with detailed instructions would be highly appreciated!

**Comment by Sandy4321** [comment]
Jeremy

I did not find some RNN based theano source code in this project
only search gave me
sunny-side-up-master_mar7\src\examples\tufs_cnn.py
'''
Model below is based on paper by Xiang Zhang "Character-Level Convolutional
Networks for Text Classification" (http://arxiv.org/abs/1509.01626) paper
was
formerly known as "Text Understanding from Scratch" (
http://arxiv.org/pdf/1502.01710v4.pdf)

THEANO_FLAGS=mode=FAST_RUN,device=gpu1,floatX=float32 python tufs_cnn.py
'''

**Comment by coodoo** [comment]
@Sandy4321 Yes, I mentioned `sunny side up` project only because they provided tweet dataset, not because they are using RNN for sentiment analysis, I was planning to implement one with `RNN` but to no avail hence asking help here :)

**Comment by Sandy4321** [comment]
Did you checked recommend semeval 16 from git,
She uses word2vec and lastm lasagna

**Comment by coodoo** [comment]
@Sandy4321 Thanks for pointing out semeval, their char-based LSTM for sentiment analysis example looks very interesting, will have a thorough study today.

It would be prefect if there's a `RNN` implementation so that it could be run on `OpenCL` (e.g. mackbook pro) instead of `CUDA`, maybe @nicholas-leonard could help? :)

**Comment by Sandy4321** [comment]
try this
https://github.com/youssefahres/EntitySentiment

https://github.com/Vict0rSch/deep_learning/tree/master/keras/recurrent

https://github.com/itdxer/neupy/tree/release/v0.2.0

https://github.com/stevenxxiu/senti/tree/master/senti


https://github.com/dandxy89/DeepLearning_MachineLearning/tree/master/EmbeddingKeras

**Comment by Sandy4321** [comment]
and this
https://github.com/fchollet/keras/issues/1327
https://github.com/fchollet/keras/issues/631
https://github.com/fchollet/keras/issues/853

**Comment by coodoo** [comment]
Thanks for the links. 

I went through `semval16` example the other day and found it's code quite hard to understand (not sure it's due to the nature of `lasagne` or author's coding style). I also looked at various [keras examples](https://github.com/fchollet/keras/tree/d229c4784505346e6a039cf2bdd5cbca3ce9e648/examples) on LSTM but none of them are char-based.

Lastly, as a total newbie in deep learning and NLP, I'm really looking forward to examples built with torch so that it supports `cltorch` and `clnn` which can be run on macbook pro with `OpenCL` graphic card to make the computation time acceptable.

IMHO example like that could really showcase the power of `rnn` lib.

**Comment by Sandy4321** [comment]
OpenCL graphic card

is it external card?

**Comment by nicholas-leonard** [comment]
@coodoo @Sandy4321 We (me, @sagarwaghmare69, @ywelement) just completed wrapping the Twitter Sentiment140 dataset into a wrapper. @sagarwaghmare69 will be working on a example using the dataset.

**Comment by nicholas-leonard** [comment]
@coodoo @Sandy4321 https://github.com/Element-Research/rnn/blob/master/examples/twitter_sentiment_rnn.lua
