### ISSUE TITLE
Error when calling Sequencer:remember()

### ISSUE THREAD

**Issue by cjmcmurtrie** [Element-Research/rnn#149]
This did not happen until a recent update of the package. When I call Sequencer:remember() I get the following error regarding the reference to `_.contains` in Sequencer.lua:
```bash
/home/ubuntu/torch/install/bin/luajit: /home/ubuntu/torch/install/share/lua/5.1/rnn/Sequencer.lua:114: attempt to call field 'contains' (a nil value)
stack traceback:
	/home/ubuntu/torch/install/share/lua/5.1/rnn/Sequencer.lua:114: in function 'remember'
	train.lua:101: in function 'output'
	train.lua:143: in function 'construct'
	train.lua:262: in main chunk
	[C]: in function 'dofile'
	...untu/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670
```

The parts of the code that are of interest are below:
```lua
model.decoderLSTM = nn.FastLSTM(vector_dim, hidden_dec)

model.decoder = nn.Sequential()
					:add(dec_table)
					:add(nn.SplitTable(1, 2))
					:add(nn.Sequencer(model.decoderLSTM))
					:add(nn.Sequencer(nn.Linear(hidden_dec, #sequences.vocab)))

model.decoder:remember('eval')
```

It seems it is the assertion in Sequencer.lua that is producing the error:
```lua
function Sequencer:remember(remember)
   self._remember = (remember == nil) and 'both' or remember
   assert(_.contains({'both','eval','train','neither'}, self._remember), 
      "Sequencer : unrecognized value for remember : "..self._remember)
   return self
end
```
Should I try removing this assertion?

**Comment by cjmcmurtrie** [comment]
I commented out the assertion in `Sequencer.lua` and it runs as normal now. 
```
function Sequencer:remember(remember)
   self._remember = (remember == nil) and 'both' or remember
   -- assert(_.contains({'both','eval','train','neither'}, self._remember), 
   --   "Sequencer : unrecognized value for remember : "..self._remember)
   return self
end
```

**Comment by nicholas-leonard** [comment]
@cjmcmurtrie `_` is a global variable that points to the moses package. You probably redefined it somewhere. I just updated the Sequencer to work around the issue. Please try again and let me know. Thanks for raising the issue :)

**Comment by cjmcmurtrie** [comment]
Hi Nicholas, sorry for the delay in getting back, it's been a busy week.

I re-installed the package on a fresh Torch install (which I needed for a new project) and it works fine now. Thanks very much for looking into it!
