### ISSUE TITLE
Accepting Tensors instead of tables as inputs for Sequencer?

### ISSUE THREAD

**Issue by juesato** [Element-Research/rnn#151]
What is the reasoning behind taking inputs as a table of length seq_len, with elements as Tensors with shape batch_size x feat_size as opposed to just a Tensor with shape seq_len x batch_size x feat_size? Would it make sense to support both types?

**Comment by nicholas-leonard** [comment]
@juesato I have actually been asking myself that very same question. It would be nice to support both use cases. The reason for the tables is the `forget()` and `recycle()` methods and how the library originally was developed. But really, all you need to do is add a SplitTable before the Sequencer. I don't have time to implement this right now. But if you want to give it shot, feel free.

**Comment by rracinskij** [comment]
The side effect is that not all modules work easily with a sequencer. Eg, a model like
`branch1=nn.Sequential()
:add(nn.Narrow(1,1,1))
:add(nn.LookupTable(2,5))`
`branch2=nn.Sequential()
:add(nn.Narrow(1,2,1))
:add(nn.LookupTable(2,5))`
`mlp = nn.Concat(1)
:add(branch1)
:add(branch2)`
works well with a tensor or table with a single tensor within it as input. A table containing multiple tensors throws an error in nn.Narrow.

**Comment by juesato** [comment]
@nicholas-leonard Are you saying to just put a `SplitTable` in the beginning to turn the Tensor into a table of Tensor objects, and then a `JoinTable` to get it back into a Tensor at the end? If so, I can make that change and submit a pull request. I'm just not sure if this is bad because it seems like there's a lot of wasted memory (in converting between Tensors and tables of Tensors)

@rracinskij What do you mean by this? This seems to work fine for me.

`require 'rnn'

branch1=nn.Sequential() :add(nn.Narrow(1,1,1)) :add(nn.LookupTable(2,5))
branch2=nn.Sequential() :add(nn.Narrow(1,2,1)) :add(nn.LookupTable(2,5))
mlp = nn.Concat(1) :add(branch1) :add(branch2)

t1 = torch.Tensor({1,2})
print(mlp:forward(t1))

mlp_seq = nn.Sequencer(mlp)
t2 = torch.Tensor({2,1})
print(mlp_seq:forward({t1,t2}))`

**Comment by rracinskij** [comment]
@juesato You are right, sorry. It looks like that my error was not directly related to adding a sequencer.

**Comment by nicholas-leonard** [comment]
@juesato I mean that if your input to the model is a tensor, you can split it into a table using SplitTable. And that if you want the output back as a Tensor, you can use JoinTable. It wouldn't be as simple as modifying Sequencer to do that internally.

**Comment by juesato** [comment]
@nicholas-leonard Gotcha. Yeah, that's what I've been doing so far. I'll think about how I'd modify Sequencer internally and if it's straightforward enough I'll do it.

**Comment by rracinskij** [comment]
@juesato Update: example above accepts a table of tensors with size 2 as inputs, but throws an error if the input tensors have size 1x2. Maybe this finding will spare some debugging time for someone.

**Comment by nicholas-leonard** [comment]
@juesato @rracinskij You can now use Sequencer with tables thanks to #201. Should make it easier to work with [SeqLSTM](https://github.com/Element-Research/rnn#rnn.SeqLSTM).

**Comment by juesato** [comment]
Oh cool! Thanks for fixing this!

**Comment by rracinskij** [comment]
Thanks a lot!
