### ISSUE TITLE
examples/encoder-decoder-coupling.lua

### ISSUE THREAD

**Issue by htw2012** [Element-Research/rnn#153]
there you give me three inputs,like :
```lua
local encInSeq = torch.Tensor({{1,2,3},{3,2,1}})
local decInSeq = torch.Tensor({{1,2,3,4},{4,3,2,1}})
local decOutSeq = torch.Tensor({{2,3,4,1},{1,2,4,3}})
```
 I don't know how to get decInSeq. Can you explain it? Thank you? @nicholas-leonard

**Comment by htw2012** [comment]
I think there's some wrong with decInSeq and decOutSeq.
I don't know why we train need decInSeq , it can get decInSeq by prevous decoder's output?

**Comment by nicholas-leonard** [comment]
@douwekiela @cheng6076 Can you guys help him out with this?

**Comment by douwekiela** [comment]
@htw2012: you are right that you can compute decInSeq and decOutSeq from a single sequence, simply by shifting it by one (e.g. for "hello", from "h" we predict "e", from "he" we predict "l", etc.). See also my reply at https://github.com/Element-Research/rnn/issues/68.

@nicholas-leonard: the second sample in decOutSeq should probably be something like {3,2,1,1}, assuming we take 1 to be padding. I don't have time to submit a PR for that but maybe that's what got @htw2012 confused in the first place?

**Comment by cheng6076** [comment]
@douwekiela is right. This is just a toy example. In practice, we can get decInSeq and decOutSeq from a single sequence.
Let's assume we are doing sequence to sequence transduction, the source sentece is 'how are you', and the target is 'i am ok'. Then decInSeq in the case (with mini-batch size 1) is the index of [some start symbol, 'i', 'am'], decOutSeq is the index of ['i', 'am', 'ok']. During training, we can feed the gold sequence as input to the decoder, to help it learn from previous wrong predictions. However, at test time we have to feed the prevous decoder's output as input to the next hidden state of the decoder, just as you said @htw2012

**Comment by htw2012** [comment]
@douwekiela @cheng6076 @nicholas-leonard Thanks for your replys, I get it.The toy example is lack of test procedures. Maybe we can code some test procedures for encoder-decoder model,because it is a necessory parts for  encoder-decoder model use.
