### ISSUE TITLE
Is it possible to see which indices are masked using MaskZero or MaskZeroCriterion?

### ISSUE THREAD

**Issue by juesato** [Element-Research/rnn#154]
For example, something along the lines of `local maskedIndices = criterion.maskZero`? In my case, I'd like to compute precision/recall, so I need to ignore the outputs at masked indices.

**Comment by nicholas-leonard** [comment]
`criterion.zeroMask` will have what you need : https://github.com/Element-Research/rnn/blob/master/MaskZeroCriterion.lua#L62

**Comment by juesato** [comment]
Thanks Nicholas!

For others with this problem, my issue was due to the fact that I had the `MaskZeroCriterion` wrapped by a `SequencerCriterion`. I was able to solve this issue by calling something like `criterion:getStepCriterion(3).zeroMask` where `criterion:getStepCriterion()` gets the Criterion which is wrapped by `SequencerCriterion`.
