### ISSUE TITLE
Encoder-Decoder Architectures

### ISSUE THREAD

**Issue by hannes-brt** [Element-Research/rnn#16]
Hi,

I was looking to implement an encoder-decoder LSTM architecture (like http://papers.nips.cc/paper/5346-sequence-to-sequence-learning-with-neural-networks.pdf). But the problem I have is that there doesn't seem to be a good way to pass the output of the encoder network to the decoder network as the hidden state.

More precisely, in `LSTM:updateOutput`, `prevOutput` is initialized to zero:
```lua
   if self.step == 1 then
      prevOutput = self.zeroTensor
```
However, I would need a way to pass in `output[-1]` from the encoder network into the decoder network as `prevOutput`. Of course, I will also need the gradients to flow back into the encoder properly.

Is there a way to achieve this setup with your current architecture?

Thanks a lot!

**Comment by nicholas-leonard** [comment]
One option is to define your own nn.MyLSTM class which inherits nn.LSTM. Then you can over-ride the functions you want with the functionality you need. 
Another option would be to set these manually. I think something like this might work:
```lua
lstm = nn.LSTM() -- my decoder
lstm.rho = rho -- the size of the sequence you will feed in
lstm.step = 2 -- this will tell it that it has already done the first state.
--tell it what the previous step should be :
lstm.outputs[1] = nn.rnn.recursiveCopy(lstm.outputs[1], myencoderoutput) 
lstm.cells[1] = nn.rnn.recursiveCopy(lstm.cells[1], myencodercell)
lstm:forward( --... etc. 
```

**Comment by hannes-brt** [comment]
Thank you for the answer Nicholas, 

I'll try these out and see if they work for my task.

**Comment by douwekiela** [comment]
@nicholas-leonard, would you mind clarifying your example? I just tried a simple test case where I generate from different "thought vectors" foo and bar, but their content does not seem to affect the network output:

```
torch.manualSeed(123)

foo = torch.randn(10)
bar = torch.randn(10)
input = torch.Tensor({1,2,3,4})

net = nn.Sequential():add(nn.LookupTable(4, 10)):add(nn.SplitTable(1, 10))

lstm = nn.LSTM(10, 10)
lstm.rho = 4

net:add(nn.Sequencer(lstm))

pprint(net:forward(input))

lstm.step = 2
lstm.outputs[1] = nn.rnn.recursiveCopy(lstm.outputs[1], foo)
lstm.outputs[1] = nn.rnn.recursiveCopy(lstm.outputs[1], foo)

pprint(net:forward(input))

lstm.step = 2
lstm.outputs[1] = nn.rnn.recursiveCopy(lstm.outputs[1], bar)
lstm.outputs[1] = nn.rnn.recursiveCopy(lstm.outputs[1], bar)

pprint(net:forward(input))
```

The printed output is the same in each case. Am I missing something? Looking at the code (e.g. https://github.com/Element-Research/rnn/blob/master/LSTM.lua#L156) it doesn't seem to use `lstm.outputs[self.step-1]` but `lstm.output`, which is the previous output and empty at the first forward pass.

**Comment by nicholas-leonard** [comment]
@hannes-brt @douwekiela Hi guys. Since you guys really want this, I added this kind of capability to the package. You can set the initial hidden state of the LSTM by setting : `lstm.userPrevOutput = foo`. Example :  
```lua
require 'rnn' 

torch.manualSeed(123)

foo = torch.randn(10)
bar = torch.randn(10)
input = torch.Tensor({1,2,3,4})

net = nn.Sequential():add(nn.LookupTable(4, 10)):add(nn.SplitTable(1, 10))

lstm = nn.LSTM(10, 10)
lstm.rho = 4

net:add(nn.Sequencer(lstm))

print("vanilla", unpack(net:forward(input)))

lstm.userPrevOutput = nn.rnn.recursiveCopy(lstm.userPrevOutput, foo)

print("foo", unpack(net:forward(input)))

lstm.userPrevOutput = nn.rnn.recursiveCopy(lstm.userPrevOutput, bar)

print("bar", unpack(net:forward(input)))
```

You can retrieve its gradient after a call to backward via the `lstm.userGradPrevOutput` Tensor.

Note that you will need to update the repository for these changes to take effect.

**Comment by douwekiela** [comment]
This is great, thanks @nicholas-leonard!
