### ISSUE TITLE
sequence-wise batch normalization

### ISSUE THREAD

**Issue by willfrey** [Element-Research/rnn#161]
Do you have any suggestions for implementing sequence-wise batch normalization as described in [this paper](http://arxiv.org/abs/1510.01378)?

To summarize the idea: Suppose we have a minibatch consisting of sequences with variable length. To package them up into a minibatch, one would pad the shorter sequences with zeros to match the length of the longest sequence in the minibatch. Intuitively, to compute batch normalization on the minibatch of padded sequences, you would stack the non-padded frames in the minibatch along the time axis and compute the relevant statistics. This ensures that the padded frames don't degrade the statistics being computed.

I have two rough ideas:
* Perhaps a clever use of `nn.Select()` would work? It would be easy to get the "true length" of my sequences contained in my minibatch before I do a forward pass. However, I would have to modify that layer of my model every minibatch, which I think is possible but wouldn't be ideal.
* Alternatively, I think that `nn.ParallelTable()` might work because I could take a table consisting of the unpadded sequences as my initial input. The problem here would be using `nn.Padding` to pad the variable-length sequences to a uniform length.

Any suggestions are appreciated. If you don't think this is possible, would you please consider this as a feature request?

@soumith Would this more appropriate as an issue on the @torch nn Github repo?

Thanks!

**Comment by willfrey** [comment]
I just noticed the new `TrimZero` module. This seems to be what I'm looking for. Can you confirm?

**Comment by willfrey** [comment]
`TrimZero()` with 0 padding on the front appears to do exactly what I need. Hooray!

Closing this.

**Comment by nicholas-leonard** [comment]
@willfrey Glad you found what you needed :)
