### ISSUE TITLE
MaskZero in the Sequence to One case

### ISSUE THREAD

**Issue by yjxiao** [Element-Research/rnn#165]
Hi! Thanks for this great package. I'm implementing something similar to the sequence to one example with masking. `MaskZero` gives zero outputs in the padded time steps so I assume selecting the last time step wouldn't work. Do you have any suggestions on this? Thanks!

**Comment by yjxiao** [comment]
Left padding is possible, but this issue still exists in the bidirectional rnn case.

**Comment by nicholas-leonard** [comment]
@yjxiao For bidirectional, you would need to implement your BRNN manually (using two Sequencers, two rnns, etc). The trick would be to forward two sequences : one with left padding, one with right padding.

**Comment by yjxiao** [comment]
@nicholas-leonard Thanks! It's probably the most suitable approach at the moment.
