### ISSUE TITLE
How to initialize a RNN model ?

### ISSUE THREAD

**Issue by Beanocean** [Element-Research/rnn#173]
In some implements of RNNs such as [char-rnn](https://github.com/karpathy/char-rnn) and [Oxford machine learning course parctical6](https://github.com/oxford-cs-ml-2015/practical6), we need to randomly initialize the parameters of networks using a  certain distribution (normal distribution or something else). Is there a equivalent operation in this RNNs library ? Or I need to do it myself.

**Comment by nicholas-leonard** [comment]
@Beanocean You can do it the same way as those packages:
```lua
parameters = rnn:getParameters()
parameters:uniform(-0.1, 0.1)
```

**Comment by Beanocean** [comment]
@nicholas-leonard I know, thank you very much.
