### ISSUE TITLE
Modules that carry state

### ISSUE THREAD

**Issue by xq111** [Element-Research/rnn#177]
I'm trying to make a module that carries around a table into which other modules can insert entries, but I'm having trouble making it work with `Sequencer`. 

My module takes in an index `i` and value `v` and inserts the pair `{i, v}` into the table it carries around:
```
local UpdateTable, parent = torch.class("nn.UpdateTable", "nn.Module")

function UpdateTable:__init(tbl)
    parent.__init(self)
    self.tbl = tbl
end

function UpdateTable:updateOutput(inputTbl)
    local val, ind = unpack(inputTbl)
    self.tbl[#self.tbl + 1] = {ind[1], val[1]}
    self.output = self.tbl
    return self.output
end

function UpdateTable:updateGradInput(input, gradOutput)
    self.gradInput = {torch.Tensor({0}), torch.Tensor({0})}
    return self.gradInput
end
```
This module behaves as I want it to when I `forward` through it iteratively:

```
local inpTbl = { {torch.Tensor({1}), torch.Tensor({1})},
                 {torch.Tensor({2}), torch.Tensor({2})},
                 {torch.Tensor({3}), torch.Tensor({3})} }

local layer = nn.UpdateTable({})
for _, inp in ipairs(inpTbl) do
    print(layer:forward(inp))
end
```
produces

```
{{1, 1}}
{{1, 1}, {2, 2}}
{{1, 1}, {2, 2}, {3, 3}}
```

I wanted the module to carry around its `tbl` field when wrapped in a `Sequencer`, so I tried adding a `stepClone` method that copied `tbl`.

```
function UpdateTable:stepClone(shareParams, shareGradParams)
    local out = self
    out.tbl = self.tbl
    return out
end
```
But two unexpected things happen when I `forward` the example table above. First, this code
```
local net1 = nn.Sequencer(nn.UpdateTable({}))
print(net1:forward(inpTbl))
```
produces
```
{ {{1, 1}, {2, 2}, {3, 3}},
  {{1, 1}, {2, 2}, {3, 3}},
  {{1, 1}, {2, 2}, {3, 3}} }
```
Second, when I put the module in a `Sequential` container: 
```
local net2 = nn.Sequencer(nn.Sequential():add(nn.UpdateTable({})))
print(net2:forward(inpTbl))
```
I get
```
{ {{1, 1}},
  {{2, 2}},
  {{3, 3}} }
```
So I have two questions:

- Why has adding the `Sequential` change anything? I guess I expected  (without really understanding how it works) the automatic call to `Recursor` to fix that.
- Is there a way I can change my module so that the `Sequencer` produces the same result as iterated calls to `forward' (i.e. the first result above)? Thanks!

**Comment by nicholas-leonard** [comment]
@xq111 Sorry for the delay. You should try passing around tensors instead of numbers. Torch doesn't really support the latter.
