### ISSUE TITLE
Changing glimpse depth does not work on CUDA

### ISSUE THREAD

**Issue by parthchadha** [Element-Research/rnn#181]
Hello,
I have been recently working with the Recurrent visual attention example. I am unable to train the model on GPU if I change the Glimpse depth from the default value of '1'.
Can you please look into this?

Thanks!

**Comment by parthchadha** [comment]
The problem was created by nn.DontCast(). 
I experimented with a test script and found that without DontCast() the model trains on GPU with any value of Glimpse depth. If I use DontCast(), the model trains on GPU only if Glimpse depth is 1.
I am exploring the reason of why this happens.

**Comment by nicholas-leonard** [comment]
@parthchadha where you able to identify the problem?

**Comment by parthchadha** [comment]
Hello @nicholas-leonard . Sorry for delayed response. 
Can you please let me know what was the need for DontCast?
Anyway, SpatialGlimpse module calls either nn.SpatialAveragePooling or nn.SpatialReSampling module if depth is greater than 1. I guess because of the use of Dont Cast, these submodules are not being cast to CUDA and hence these modules are being implemented on CPU.
Please let me know your inputs for the same.
Thanks!

**Comment by nicholas-leonard** [comment]
SpatialReSampling doesn't have a GPU implementation. So it requires DontCast. But if SpatialAveragePooling is used, DontCast isn't necessary.
