### ISSUE TITLE
Slow LSTM speed relative to theano.

### ISSUE THREAD

**Issue by Torkoal** [Element-Research/rnn#182]
Recently, a benchmark was made comparing the `rnn` package to Theano, and found Theano to be much much faster (the benchmark can be found [here](https://github.com/glample/rnn-benchmarks)). This is concerning. It's currently unknown if other implementation of RNNs in torch are faster ([torch-rnn](https://github.com/jcjohnson/torch-rnn) might be), but it seems some improvement to speed could be made. I'm hope to revisit this problem when I have less deadlines to deal with, but just wanted to hear other's thoughts. Thanks.

**Comment by iikulikov** [comment]
as I got, in this benchmark they did not use nngraph. (at least in the source code [here])(https://github.com/glample/rnn-benchmarks/blob/master/torch/rnn.lua) With nngraph FastLSTM is faster.

**Comment by Torkoal** [comment]
How do you set the variable? Do you do it before you build `rnn`? I will submit a pull request to make the change.

**Comment by iikulikov** [comment]
Should be something like in this simple [example](https://github.com/Element-Research/rnn/blob/7d2afd2b5fe51f059a2c1c41bb5ff18045bd7b4e/examples/recurrent-language-model.lua#L83-L86), so you just set the flag.

**Comment by nicholas-leonard** [comment]
@Torkoal Thanks for updating that benchmark :)

**Comment by nicholas-leonard** [comment]
@Torkoal Also feel free to try to improve the speed of the package. I know for sure that the LSTM module could benefit from a usenngraph = true implementation.

**Comment by nicholas-leonard** [comment]
I also submitted a PR with some improvements to the benchmark : https://github.com/glample/rnn-benchmarks/pull/5
