### ISSUE TITLE
LookupTable for each variable in the multivariate time series example

### ISSUE THREAD

**Issue by rracinskij** [Element-Research/rnn#185]
Hi, I’m trying to change the rnn input layer in the recurrent-time-series.lua example from nn.Linear(opt.multiSize, opt.hiddenSize) to separate LookupTables for each quantised variable (opt.multiSize was changed to 2, opt.batchSize to 1, LookupTable to (2,5) for simplicity), but all approaches listed below generate errors at some stage, primarily at rnn:backward(). Is there any feasible way to do it? Thank you.

```
local branch1=nn.Sequential() :add(nn.Narrow(1,1,1)) :add(nn.LookupTable(2,5))
local branch2=nn.Sequential() :add(nn.Narrow(1,2,1)) :add(nn.LookupTable(2,5))
local b = nn.Concat(1) :add(branch1) :add(branch2)
local inpLayerB = nn.Sequential():add(b):add(nn.Reshape(1,10))
```
or

```
local inpLayerC = nn.Sequential()
inpLayerC:add(nn.SplitTable(2)) --split input at dim 2
local c = nn.ParallelTable()
c:add(nn.LookupTable(2, 5)) -- apply to first variable
c:add(nn.LookupTable(2, 5)) -- apply to second variable
inpLayerC:add(c)                 
inpLayerC:add(nn.JoinTable(1))
inpLayerC:add(nn.Reshape(1,10))
```
or

```
local inpLayerD = nn.Sequential()
local d = nn.Parallel(2,1);  --split input at dim 2
d:add(nn.LookupTable(2,5)) -- apply to first variable
d:add(nn.LookupTable(2,5))  -- apply to second variable
inpLayerD:add(d)
inpLayerD:add(nn.Reshape(1,10))
```

**Comment by nicholas-leonard** [comment]
@rracinskij Yeah this is a limitation of LookupTable as it does not generate any gradInput when calling updateGradInput or backward. So any modules before LookupTable (like the Narrows above) or encapsulating it (like Parallel), should have their `updateGradInput` overwritten by something like this : 

```lua
nn.Parallel.updateGradInput = function() return end
```

I think the last example is the best.
