### ISSUE TITLE
(bug) casting to "long" in Recurrent.lua 

### ISSUE THREAD

**Issue by rosenfeldamir** [Element-Research/rnn#186]
In line 27 in Recurrent.lua , I saw the following :
`elseif ts == 'table' then
      start = nn.Add(torch.LongStorage(start))`

Doesn't this cast the table's contents to "long", regardless of their actual type?
Thanks,
-Amir

**Comment by nicholas-leonard** [comment]
@rosenfeldamir In that case the `start` table is expected to look something like this : `{1,2,3,4}`. So it has no type under than being a Lua table containing Lua numbers. So year, it casts the table's content to long regardless of their actual type :) But if the table doesn't contain numbers, it will fail and yield and error message.

**Comment by rosenfeldamir** [comment]
@nicholas-leonard , looks to me like this casting could cause unexpected behavior...
