### ISSUE TITLE
[Clarification] Implementing LSTM with nn.Recurrence?

### ISSUE THREAD

**Issue by willfrey** [Element-Research/rnn#188]
To implement an LSTM with `nn.Recurrence` would you expect the input to be:
`{input(t), {output(t-1), cell(t-1)}}`?

Just a clarification question before I start trying to make it work!

Thanks.

**Comment by willfrey** [comment]
I read through the documentation in the actual Recurrence file and that cleared things up for me. It looks like output(t) can be a tensor or a table. 

Closing this!

**Comment by nicholas-leonard** [comment]
@willfrey Glad you were able to solve this on your own. Don't hesitate if you have more questions.
