### ISSUE TITLE
Possible usage of a trained rnnlm?

### ISSUE THREAD

**Issue by coodoo** [Element-Research/rnn#191]
Just went through the [`rnnlm`](https://github.com/Element-Research/rnn/blob/master/examples/recurrent-language-model.lua) example and sort of understood what it's doing (nice job btw!)

I'm wondering once the model is trained, what's the possible usages of that `rnnlm`? Could it be further used for sentiment analysis or other text classification tasks? Thanks.

**Comment by coodoo** [comment]
[Solved](https://github.com/torch/nn/issues/747)

**Comment by nicholas-leonard** [comment]
@coodoo Good stuff!
