### ISSUE TITLE
Implementation Request : Revisit Long Short-Term Memory

### ISSUE THREAD

**Issue by Kaixhin** [Element-Research/rnn#192]
[Revisit Long Short-Term Memory: An Optimization Perspective](http://hgpu.org/?p=13390) has some interesting results on using steeper (parameterised) sigmoids to make the gates in LSTM more binary. I'll soon be submitting a PR to `torch/nn` with `nn.PSigmoid` which would be needed to implement this.

**Comment by nicholas-leonard** [comment]
@Kaixhin Yeah that seems promising. We could add a switch to the LSTM to use PSigmoid.
