### ISSUE TITLE
What if I don't want to finetune part of the model

### ISSUE THREAD

**Issue by vyouman** [Element-Research/rnn#194]
Hi, I'm trying to use the RecurrentAttention module and want to change the visual core of the glimpse network to be a CNN instead of a linear layer. But I just want to regard the CNN as a tool and don't want to finetune it. How can I do it? Thanks.

**Comment by juesato** [comment]
You could make two networks, one with the convolutional layer, and the other one with everything else, and then combine them using `nn.Sequential`. Then just only call backwards on the other (non-convolutional layer).

**Comment by nicholas-leonard** [comment]
@vyouman If you don't want a `module` to learn, you can do : 
```lua
module.accGradParameters = function() return end
```
If the module is located at the input of your model, you can even disable backpropagation completely via `dontBackward` : https://github.com/Element-Research/dpnn/blob/master/Module.lua#L511-L516 .

**Comment by vyouman** [comment]
@nicholas-leonard @juesato Thanks. I'll have a try.
