### ISSUE TITLE
question: issues with table output for nn.Recurrence

### ISSUE THREAD

**Issue by willfrey** [Element-Research/rnn#197]
I'm attempting to implement `nn.FastLSTM` with `nn.Recurrence` as a learning exercise. The only modification I thought that I'd need to make was to add another `nn.FlattenTable()` to adapt for the input being `{ input, {prevOutput, prevCell} }` instead of `{input, prevOutput, prevCell}`.

I get issues with the `nn.SelectTable(3)` when it tries to get the `prevCell` value. I suspect it's because the way I'm instantiating `nn.Recurrence` isn't forwarding through a zero tensor for the prevCell.

I'm digging through the comments in `nn.Recurrence` now but any guidance would be appreciated. At present, I'm calling `lstm = nn.Recurrence(rm, hiddensize, 1)` where `rm` is essentially `seq` from `nn.FastLSTM` with the extra `nn.FlattenTable` call and the `self.inputSize` and `self.outputSize` declared outside of the scope of the module class (to make it work in the first place).

Apologies if this is a convoluted question.

**Comment by willfrey** [comment]
As usual, your tests sorted out the issue.

I need `outputSize` to be `{{hiddensize}, {hiddensize}}`, [as it is here. ](https://github.com/Element-Research/rnn/blob/4192069daf263cdd8e55b3b140371e73092fc8c6/test/test.lua#L3445)

**Comment by nicholas-leonard** [comment]
@willfrey Glad you were able to sort that out!
