### ISSUE TITLE
How to check out the parameters?

### ISSUE THREAD

**Issue by edward-zhu** [Element-Research/rnn#20]
Hi,

It seems that the lib has not implemented `parameters()` in `nn.Module`, so I could hardly get access to the parameters of RNN modules unless change the codes of the library itself.

I'm wonder if is there any way to check out the parameters outside the class like the `getParameters()` in `nn.Module`?

Edward

**Comment by nicholas-leonard** [comment]
The nn.Module inherits the `parameters()` method of the original nn.Module class found in the nn package. The model could not be properly trained without that method. You sure you can't access `parameters()`?

**Comment by edward-zhu** [comment]
Sorry, I have not made it clear.

The problem is in the `nn.BiSequencer()`

Here's my net. I ran it, and there is nothing shown.

```lua
local net = nn.Sequential()
net:add(nn.Dropout(DROPOUT_RATE))
net:add(nn.SplitTable(1))
net:add(nn.BiSequencer(nn.LSTM(input_size, hidden_size)))

params, grads = net:getParameters()

print(grads)
```

However, if I replace the `nn.BiSequencer()` with `nn.Sequencer()`, it will work.

**Comment by edward-zhu** [comment]
Sorry, It might be my fault. It finally gets OK, and I'm checking out what have happened.

Thanks for your help!

**Comment by nicholas-leonard** [comment]
Tell me about it. Computers can be so weird some times... Thanks anyway. And don't hesitate to open more tickets!
