### ISSUE TITLE
Large memory footprint for trained LSTM

### ISSUE THREAD

**Issue by FBMachine** [Element-Research/rnn#200]
Hi,
When saving out a trained seq-to-seq model, it's taking up over 4GB on disk. A quick estimate of the space needed for the parameters given our model architecture is closer to 10MB, so I'm assuming most of this is due to the batch size and sequence length.

Since at run-time we won't need most of this with the trained model, is there a way to shed most of these tensors that are only needed during training?

Thanks!

**Comment by JoostvDoorn** [comment]
Try :clearState()

**Comment by nicholas-leonard** [comment]
@FBMachine You could also try : 
```
require 'dpnn'
model = nn.Serial(model)
model:mediumSerial()
```

**Comment by FBMachine** [comment]
model:mediumSerial() made a huge difference. Thanks!
