### ISSUE TITLE
Error during backprop in RNN

### ISSUE THREAD

**Issue by rajarshd** [Element-Research/rnn#202]
Hi! - I am facing this weird error during the backward step through the RNN. Below is the minimal code to explain the scenario
```lua
require 'torch'
require 'nn'
require 'rnn'

embeddingDim = 5
hiddenSize = 5
seq_length = 10
batch = 32
-- recurrent module
rm = nn.Sequential()
	:add(nn.ParallelTable()
      :add(nn.Linear(embeddingDim, hiddenSize))
      :add(nn.Linear(hiddenSize, hiddenSize)))
   :add(nn.CAddTable())
   :add(nn.Sigmoid())

rm = nn.MaskZero(rm,1) --to take care of padding.
net = nn.Sequential()
	:add(nn.SplitTable(2))
	:add(nn.Sequencer(nn.Recurrence(rm, hiddenSize, 1)))
	:add(nn.SelectTable(-1))
	:add(nn.Linear(hiddenSize,1))
inputs = torch.randn(batch, seq_length, embeddingDim)
output = net:forward(inputs)
targets = torch.Tensor(batch,1):zero()
criterion = nn.BCECriterion()
criterion:forward(output, targets)
df_do = criterion:backward(output, targets)
net:backward(inputs, df_do)
```

I get the following error
```
/usr/local/torch/install/bin/luajit: /usr/local/torch/install/share/lua/5.1/nn/Container.lua:69: 
In 2 module of nn.Sequential:
In 1 module of nn.Sequential:
In 1 module of nn.ParallelTable:
/usr/local/torch/install/share/lua/5.1/nn/Linear.lua:89: attempt to index local 'input' (a number value)
stack traceback:
	/usr/local/torch/install/share/lua/5.1/nn/Linear.lua:89: in function </usr/local/torch/install/share/lua/5.1/nn/Linear.lua:87>
	[C]: in function 'xpcall'
	/usr/local/torch/install/share/lua/5.1/nn/Container.lua:65: in function 'rethrowErrors'
	/usr/local/torch/install/share/lua/5.1/nn/ParallelTable.lua:27: in function </usr/local/torch/install/share/lua/5.1/nn/ParallelTable.lua:24>
	[C]: in function 'xpcall'
	/usr/local/torch/install/share/lua/5.1/nn/Container.lua:65: in function 'rethrowErrors'
	/usr/local/torch/install/share/lua/5.1/nn/Sequential.lua:75: in function 'accGradParameters'
	/usr/local/torch/install/share/lua/5.1/dpnn/Decorator.lua:21: in function 'accGradParameters'
	/usr/local/torch/install/share/lua/5.1/rnn/Recurrence.lua:155: in function '_accGradParameters'
	...al/torch/install/share/lua/5.1/rnn/AbstractRecurrent.lua:58: in function 'accGradParameters'
	/usr/local/torch/install/share/lua/5.1/rnn/Sequencer.lua:92: in function 'accGradParameters'
	/usr/local/torch/install/share/lua/5.1/nn/Module.lua:32: in function </usr/local/torch/install/share/lua/5.1/nn/Module.lua:29>
	[C]: in function 'xpcall'
	/usr/local/torch/install/share/lua/5.1/nn/Container.lua:65: in function 'rethrowErrors'
	/usr/local/torch/install/share/lua/5.1/nn/Sequential.lua:84: in function 'backward'
	fix_rnn_padding.lua:37: in main chunk
	[C]: in function 'dofile'
	...ocal/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00405800
```
However when I add a nn.Identity() in the recurrent module, everything seems to work fine. What could be going on here?
```lua
-- recurrent module
rm = nn.Sequential()
	:add(nn.Identity())
	:add(nn.ParallelTable()
      :add(nn.Linear(embeddingDim, hiddenSize))
      :add(nn.Linear(hiddenSize, hiddenSize)))
   :add(nn.CAddTable())
   :add(nn.Sigmoid())
```

**Comment by rracinskij** [comment]
@rajarshd Your code seems to be working, maybe the error is somewhere else?

**Comment by nicholas-leonard** [comment]
@rajarshd I updated torch, nn, dpnn, rnn. I cannot reproduce your error. Can you try updating these packages on your end?

**Comment by rajarshd** [comment]
Definitely! will let you know in sometime. Thanks for looking into this.

**Comment by rajarshd** [comment]
Yep, updating the libraries resolved the issue. Thanks! @nicholas-leonard , @rracinskij

**Comment by Petterhg** [comment]
Hey guys, I'm kind of new to this and have the same issue. How do I update my packages?
Thanks!

**Comment by rracinskij** [comment]
Hi @Petterhg , try `luarocks install rnn`

**Comment by Petterhg** [comment]
Hi,

Nope it doesnt work :( Under here you can see my whole session. Maybe you can see something I dont:


MacBook-Pro:~ Petter$ th



  ______             __   |  Torch7
 /_  __/__  ________/ /   |  Scientific computing for Lua.
  / / / _ \/ __/ __/ _ \  |  Type ? for help
 /_/  \___/_/  \__/_//_/  |  https://github.com/torch
                          |  http://torch.ch

                                                                      [0.0001s]
th> require 'nn';
                                                                      [0.1002s]
th> net = nn.Sequential()
                                                                      [0.0001s]
th> input=torch.rand(1,32,32)
                                                                      [0.0001s]
th> gradInput=net:backward(input, torch.rand(10))
/Users/Petter/torch/install/share/lua/5.1/nn/Container.lua:63: attempt to index local 'module' (a nil value)
stack traceback:
/Users/Petter/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
/Users/Petter/torch/install/share/lua/5.1/nn/Sequential.lua:88: in function 'backward'
[string "gradInput=net:backward(input, torch.rand(10))"]:1: in main chunk
[C]: in function 'xpcall'
/Users/Petter/torch/install/share/lua/5.1/trepl/init.lua:670: in function 'repl'
...tter/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:199: in main chunk
[C]: at 0x010da1cd10
                                                                      [0.0001s]
th>














26 aug. 2016 kl. 08:41 skrev Ricard Racinskij <notifications@github.com<mailto:notifications@github.com>>:


Hi @Petterhg<https://github.com/Petterhg> , try luarocks install rnn

**Comment by rracinskij** [comment]
@Petterhg it looks like your model is missing any layers (like `net:add(nn.Recurrent(...))`). Please check out the examples section.
