### ISSUE TITLE
Sequencer documentation

### ISSUE THREAD

**Issue by jsuit** [Element-Research/rnn#205]
https://github.com/Element-Research/rnn#rnn.Sequencer

      input = {torch.randn(3,4), torch.randn(3,4), torch.randn(3,4)}
      rnn:forward(input[1])
      rnn:forward(input[2])
      rnn:forward(input[3])

What is rnn here?

**Comment by nicholas-leonard** [comment]
@jsuit It is an AbstractRecurrent instance like Recurrent, Recurrence, LSTM, GRU or FastLSTM.
