### ISSUE TITLE
model:getParameters and memory blowup?

### ISSUE THREAD

**Issue by jsuit** [Element-Research/rnn#206]
`model` = nn.Sequential()

     model:add(nn.Sequencer(nn.LookupTable(hiddenSize, hiddenSize)))
     model:add(nn.Sequencer(nn.FastLSTM(hiddenSize, hiddenSize, rho)))
     model:add(nn.Sequencer(nn.Linear(hiddenSize, nIndex)))
     model:add(nn.Sequencer(nn.LogSoftMax()))`

 Then when I do `model:getParameters()`, the memory usage blows up from 3-5 GB to 17 GB? Am I doing something wrong? Why the memory blowup

**Comment by nicholas-leonard** [comment]
@jsuit model:getParameters() should momentarily double the memory footprint of the model. This is because it allocates a single contiguous storage for the entire model. But in your case it seems to be doing more than that. Are you using `nn.FastLSTM.usenngraph = true`?

**Comment by jsuit** [comment]
yes.

**Comment by nicholas-leonard** [comment]
@jsuit Correct me if I am wrong, but this seems to be an issue with nn. When I try this I get the same kind of issue : 
```lua
require 'nn'

hiddenSize = 1000
nIndex = 100000


model = nn.Sequential()
model:add(nn.LookupTable(nIndex, hiddenSize))
model:add(nn.Linear(hiddenSize, nIndex))
model:add(nn.LogSoftMax())

print("getParameters()")
model:getParameters()
```
