### ISSUE TITLE
Does Recurrence modify 'self.output' of the module it's wrapping?

### ISSUE THREAD

**Issue by ssampang** [Element-Research/rnn#208]
I've created a custom ReinforceGamma module, which is similar to the ReinforceNormal module from dpnn. For my purposes, however, I need it to add on the sample from the distribution to the value sampled at the previous timestep. To do this, I've wrapped the module with a Recurrence module. What I've noticed (using print statements on [this line](https://github.com/ssampang/HeartbeatAtt/blob/master/ReinforceGamma.lua#L112)) is that the self.output of ReinforceGamma at each timestep is not storing its values correctly. If I print out the self.output on the forward pass and the backward pass, they don't match. I can rectify this issue by modifying Recurrence to pass in the current timesteps output (right now it only passes in the previous timestep's output) and using that instead of self.output, but I was wondering if anyone could shed some light onto my problem. Shouldn't the module be remembering its state? Is Recurrence messing with the output of its contained modules?

**Comment by nicholas-leonard** [comment]
Can you provide a small snippet of code that fails for your use case? I can try to debug it so that it doesn't.

**Comment by nicholas-leonard** [comment]
Also, try with updated rnn. Fixed a bug in https://github.com/Element-Research/rnn/commit/e8dc44d42fcbabcb3d5e7bc24e63fcabe1ab7dbf today.

**Comment by ssampang** [comment]
Sorry, it was my mistake - caused by self.output sharing storage with the input instead of allocating its own.

**Comment by nicholas-leonard** [comment]
@ssampang If you get it working, would love to see your ReinforceGamma code added to dpnn!

**Comment by ssampang** [comment]
@nicholas-leonard I was going to ask about that. Does it matter that it depends on torch.randomkit to sample the gamma distribution and cephes to calculate the digamma function (for the gradient)? I would definitely love to contribute back to dpnn!

**Comment by nicholas-leonard** [comment]
ideally, you can just import them inside the constructor. That way it doesn't introduce hard dependencies to the dpnn. Would that work?

**Comment by ssampang** [comment]
Yeah should be fine. I'll submit a PR then when I have it ready.
