### ISSUE TITLE
How to avoid explicit calls to cuda()

### ISSUE THREAD

**Issue by ssampang** [Element-Research/rnn#209]
Is there a way that I can avoid explicit calls to cuda? I've written a custom module and wrapped it with a Recurrence. I don't make any explicit calls to `cuda()` or create CudaTensors myself, but I use things like `local mean = input.new()`. This works well until I try to use the output from the previous timestep passed to me from Reccurrence, which is a DoubleTensor. Is there anyway I can avoid calling cuda() on it?

Also, is this the appropriate place to ask questions like this?

**Comment by nicholas-leonard** [comment]
@ssampang Not sure what you mean. If your input is cuda, than your model should also probably be cuda. If your model is cuda, your input should also probably be cuda (unless you use nn.Convert or nn.Copy). 

Its also usually a bad idea to mix an match modules of different types. Is this what you are doing? 

Also why do you want to avoid casting to cuda?

**Comment by ssampang** [comment]
I'm just trying to write good code that can work both on and off the gpu. Studying your code, it seems like you also avoid explicit conversions to cuda, and instead rely on the Experiment:cuda() function to set all tensor types to CudaTensor if that's what the user wants. Is this incorrect?

From my understanding, my model is cuda, and my input is also cuda. My problem arises [here](https://github.com/ssampang/HeartbeatAtt/blob/master/ReinforceGamma.lua#L68). I'd like to remove the explicit conversion of `lastOutput` (set at the beginning of the function) to cuda simply in the interest of following the general conventions I'm seeing.

**Comment by nicholas-leonard** [comment]
`lastOutput` is the part of the input : https://github.com/ssampang/HeartbeatAtt/blob/master/ReinforceGamma.lua#L27 . Which means your should simply make sure that it has the same type as the model. You could add a [`nn.Convert()`](https://github.com/Element-Research/dpnn#nn.Convert) before the lastOutput is fed to ReinforceGamma. It will automatically cast its input to the type of the model.

**Comment by ssampang** [comment]
I've rewritten ReinforceGamma to conform to the styles of the other Reinforce modules. I don't have this issue anymore, and will be moving the functionality of adding the previous output to an nn.Recurrent.
