### ISSUE TITLE
Recurrent module not remembering outputs

### ISSUE THREAD

**Issue by ssampang** [Element-Research/rnn#211]
I'm using the Recurrent module [here](https://github.com/ssampang/HeartbeatAtt/blob/master/recurrent-visual-attention.lua#L159), and inserted a print statement [here](https://github.com/Element-Research/rnn/blob/master/Recurrent.lua#L82) to print out the stored outputs. They weren't being stored correctly due to storage being shared, and changing that line to `self.outputs[self.step] = output:clone()` solved my issue. Not sure if this is a bug or intended, just letting you know.

**Comment by nicholas-leonard** [comment]
@ssampang This seems like an odd use of Recurrent. As you aren't using a recurrent layer, I think this is equivalent to:
```lua
locator:add(transform)
```
However, if you insist on using Recurrent, you can try : 
```lua
locator:add( nn.Recurrent( glimpseAxes, transform, nn.Copy(nil,nil,true), nn.Identity()) )
```
The Copy layer will force a clone() without reallocating memory.

**Comment by ssampang** [comment]
The only reason I needed to use nn.Recurrent was to provide a mechanism to add the previous timestep's output to that of the current timestep, and output that sum, so if the module only outputs '2' at each timestep, I want the output to actually be 2,4,8, and so on.
