### ISSUE TITLE
Example of Correct Way to use MaskZero?

### ISSUE THREAD

**Issue by jsuit** [Element-Research/rnn#214]
I'm getting warning that I'm not using MaskZero correctly. The message is "you are most likely using MaskZero the wrong way. You should probably use AbstractRecurrent:maskZero() so that it wraps the internal AbstractRecurrent.recurrentModule instead of wrapping the AbstractRecurrent module itself." I'm not terribly intuitive idea of what MaskZero does or how it works, so an example could be helpful.

More specifically,

Here is what I want to do:

local enc = nn.Sequential()
enc:add(nn.LookupTable(#indxToChar, opt.hiddenSize)
enc:add(nn.SplitTable(1, 2)) -- works for both online and mini-batch mode
local encLSTM = (nn.LSTM(opt.hiddenSize, opt.hiddenSize))
enc:add(nn.Sequencer(encLSTM))
enc:add(nn.SelectTable(-1))

dec =  nn.Sequential()
dec:add(nn.SplitTable(1, 2)) -- works for both online and mini-batch mode
local decLSTM =nn.LSTM(opt.hiddenSize, opt.hiddenSize)
dec:add(nn.Sequencer(decLSTM))
dec:add(nn.Sequencer(nn.Linear(opt.hiddenSize, opt.vocabSize),1))
dec:add(nn.Sequencer(nn.LogSoftMax()))

The input is of size batchsize x maxSeqLen, but the trick is that maxSeqLen could change size each iteration. So I compute maxSeqLen. If there are sequences that are shorter than maxSeqLen, I put a zero in that position in the input tensor. Where should I be putting nn.MaskZero? Does it even work for this?

**Comment by tobias-lang** [comment]
You can call `maskZero()` directly on all objects inheriting from `AbstractRecurrence`, like on `LSTM` objects. This will give you a `MaskZero` object wrapping your module. In your case, you would need to ensure that the zeros get appropriately propagated from the inputs to the `LSTM`, e.g., by using a `LookupTableMaskZero`.

Alternatively, you could wrap up everything together in a `Recurrence` or `Recursor` object and then call `maskZero()` there only once.
