### ISSUE TITLE
Sampling from the character like model infinite sequence.

### ISSUE THREAD

**Issue by qwertzdenek** [Element-Research/rnn#217]
Let's say I have successfully trained some model without Sequencer because it limits me. Now I want to sample infinite sequence from this model having only _rho=16_ long memory (I don't need bigger). I can sample new solution forwarding zero input, but I only get around 16 valid samples and the rest is a mess.

So I think I need to forget the oldest step module and forward step==rho in the circular buffer manner. Am I right?

```Lua
local len=300
local zeros = torch.zeros(n_visible)
local rnn_outputs = {}
rnn_outputs[0] = rnn:forward(zeros)
for t=1, len do
    -- forgot oldest step if t > rho??
    rnn_outputs[t] = rnn:forward(zeros)
    local sampled_v = rbm:forward{zeros, rnn_outputs[t-1]}
    piano_roll[t]:copy(sampled_v)
end
```

Is there some combination of _forget_ and _recycle_ capable of doing this? I don't want to forward everything and just take the last one.

It is related to my previous issue #168, but more general.

**Comment by qwertzdenek** [comment]
It is important switch to `evaluate()`. Then it should work. It was my mistake.

**Comment by nicholas-leonard** [comment]
@qwertzdenek Yes evaluate is important especially for rnns :)
