### ISSUE TITLE
includingSharedClones

### ISSUE THREAD

**Issue by glample** [Element-Research/rnn#221]
I'm not sure I understand why in AbstractRecurrent there is:

```
local r = {f()}
...
return unpack(r)
```

while in Recursor there is just:
```
local r = f()
...
return r
```

Why is it not the same, and what would be the difference with just a call to f, and a "return self" at the end of includingSharedClones?

**Comment by nicholas-leonard** [comment]
@glample The first one will correctly return multiple arguments. The second one won't. I updated Recursor to handle this : https://github.com/Element-Research/rnn/commit/0798949c400835898829871ba539e5143dba7f64 . Thanks!
