### ISSUE TITLE
Using nn.MaskZero with convolutions

### ISSUE THREAD

**Issue by RicherMans** [Element-Research/rnn#226]
Hey there, so I was wondering if nn.MaskZero works fine for convolutions, and just wrote this piece of code:
```lua
require 'nn'
require 'rnn'
seq = nn.Sequential():add(nn.SpatialConvolution(1,3,1,1))
seq:add(nn.Reshape(3*4))

sub = nn.Sequencer(nn.MaskZero(seq,3))
mdl = nn.Sequential():add(nn.SplitTable(1))
mdl:add(sub)

input = torch.Tensor(1,3,1,2,2):zero()
#Just the first batch has nonzero values, every other is zero
input[1][1] = 1
print(input)
output= mdl:forward(input)
print(output[1])
```

The model takes a 5 dimensional tensor representing  ```SEQLEN X BATCHSIZE X FEATUREMAPS X WIDTH X HEIGHT```.
So what I want to do here is just test if the output's of the model are set to zero in every row except the first one, since it has a non-zero entry ( being one ). Thus I expect the output being something nonzero-ish in the first row and every other row being zero, but all the outputs are nonzero.

Is this intended or where did I went wrong?

EDIT:

Figured it out, so to use convolutions in addition with reshape one needs to first do the masking within the convolution only operators e.g.:

```lua
convopart = nn.Sequential()
convopart:add(nn.SpatialConvolution(1,3,1,1))
convopart:add(nn.SpatialConvolution(3,3,1,1))

reshaped = nn.Sequential()


maskedconvo = nn.MaskZero(convopart,3)
reshaped:add(maskedconvo)
reshaped:add(nn.Reshape(12))

sub = nn.Sequencer(reshaped)
mdl = nn.Sequential():add(nn.SplitTable(1))
mdl:add(sub)
input = torch.Tensor(1,3,1,2,2):zero()
input[1][1] = 1

output= mdl:forward(input)

print(output[1])
```
 Works perfectly

**Comment by nicholas-leonard** [comment]
@RicherMans Glad you could get that working.

**Comment by RicherMans** [comment]
Thanks very much, I guess that solved some of my incorrect thinking
