### ISSUE TITLE
[Clarification] Access output of non-recurrent modules wrapped by a sequencer

### ISSUE THREAD

**Issue by abyravan** [Element-Research/rnn#228]
Is there any way to access the output of a non-recurrent module which is a part of a network that has been wrapped by a sequencer? Concretely, if we have the following:

```
lstm = nn.Sequencer(
   nn.Sequential()
      :add(nn.LSTM(100,100))
      :add(nn.Linear(100,100))
      :add(nn.LSTM(100,100))
   )
output = lstm:forward({torch.rand(2,100), torch.rand(2,100), torch.rand(2,100)})
linearlayer = lstm:findModules('nn.Linear')[1]
print(linearlayer.output) -- This is the output from the final step of the sequence 
```

How can I access the outputs of **linearlayer** from each step of the sequence? 

Thanks for the help!
Arun

**Comment by nicholas-leonard** [comment]
@abyravan You could access them via the getStepModule method : 
```lua
linearlayer = lstm.module:getStepModule(step):get(2)
```
where `step` is your time-step.

**Comment by abyravan** [comment]
Great, that works. If I try the same thing with the LSTM module, it does not work. With the same net as above:

```
lstm = nn.Sequencer(
   nn.Sequential()
      :add(nn.LSTM(100,100))
      :add(nn.Linear(100,100))
      :add(nn.LSTM(100,100))
   )
output = lstm:forward({torch.rand(2,100), torch.rand(2,100), torch.rand(2,100)})
print(lstm.module:getStepModule(1):get(3).output - output[1]) -- This does not work
print(lstm.module:getStepModule(1):get(3).output - output[3]) -- This works for any "step" from 1-3 
```

Is this the desired behavior?

Thanks,
Arun

**Comment by nicholas-leonard** [comment]
@abyravan Yeah the nn.LSTM.output always points to the last forward (so step 3 here). You will need to get the step module of the LSTM specifically and select its first output (i.e. the hidden state and not the cell state): 
```lua
lstm.module:getStepModule(1):get(3):getStepModule(1).output[1] - output[1]
```
A nicer interface would be a worthy enhancement.
