### ISSUE TITLE
Bidirectional RNN with variable input (feedback request for my code)

### ISSUE THREAD

**Issue by raymondhs** [Element-Research/rnn#230]
Hello, I tried to modify the BiSequencer example for variable-length input, handled using MaskZero. Here's my attempt:

https://gist.github.com/raymondhs/134af0e88558bb58cf798abe667ad9dd

The idea is based on #165 -- I created two Sequencers for forward and backward and combined them manually, there are also the original and reversed input sequence (both are right-padded). I used FastLSTM here and the LookupTable is shared. I wonder if it is also possible to share forward's LSTM with backward (e.g. by calling sharedClone())? I'd appreciate your feedback, in case I've done something incorrectly/inefficiently here. Thanks in advance! :-)

**Comment by nicholas-leonard** [comment]
@raymondhs I tried your gist script. It seems to work great. Yes you can share parameters/gradParameters between LSTMs using sharedClone. 

Could you send a PR adding this script to the examples directory? I am sure it could be useful to others.

**Comment by raymondhs** [comment]
Thanks! I have sent the PR. I'm also wondering whether we can use MaskZero in sequence-to-one situation? I checked the sequence-to-one example, it seems to use nn.SelectTable(-1) to get the last state. When we have variable length, we might want to get the last non-zero state. Any suggestions to do this?

**Comment by nicholas-leonard** [comment]
Yeah left padding would be the easiest solution.
