### ISSUE TITLE
SeqLSTM does not allow to specify grad_next_h and grad_next_c

### ISSUE THREAD

**Issue by ikostrikov** [Element-Research/rnn#231]
Hi!

Thanks for the great library!

I would like to use SeqLSTM for an encoder-decoder model. However, it doesn't allow to specify gradients with respect to the outputs of the last states of the encoder but instead sets them to zero:
https://github.com/Element-Research/rnn/blob/master/SeqLSTM.lua#L254

**Comment by JoostvDoorn** [comment]
This is not entirely correct grad_h is obtained in https://github.com/Element-Research/rnn/blob/master/SeqLSTM.lua#L267.

**Comment by ikostrikov** [comment]
@JoostvDoorn this one corresponds to the output, but not to the recurrent connection to the next states.

**Comment by JoostvDoorn** [comment]
It being the output or not doesn't really matter, if you use the output at the encoder side as well you just need to sum the gradients.

However the cell gradient really is missing. I made an example today for encoder decoder, see #233, it doesn't pass the cell gradient. Feedback is welcome.

**Comment by ikostrikov** [comment]
I meant that it would be nice to make it consistent with the other LSTM module:
https://github.com/Element-Research/rnn/blob/master/LSTM.lua#L199

**Comment by JoostvDoorn** [comment]
@ikostrikov Totally agree making it more consistent is sensible.

**Comment by nicholas-leonard** [comment]
@ikostrikov @JoostvDoorn Thanks for working on this!
