### ISSUE TITLE
Should we also need an implementation of SeqGRU? 

### ISSUE THREAD

**Issue by MultiPath** [Element-Research/rnn#235]
Hi! 
I am recently reimplementing the Sequence-to-Sequence Learning model with attention mechanism for neural machine translation. I once used Theano for it and usually I use GRU. 

Now I am very interested in torch and I think we can try the similar thing in it. However, I found the memory usage is too large if we use a nngraph-based model. I found that SeqLSTM is very fast and quite suitable for my purpose. However, I am curious if anyone has implemented similar model for GRU? Or I need to do it myself based on SeqLSTM.  

Thank you very much!

**Comment by JoostvDoorn** [comment]
Have a look here jcjohnson/torch-rnn#20

**Comment by MultiPath** [comment]
It looks awesome! Many thanks! Maybe it's good to test that cell first!

**Comment by nicholas-leonard** [comment]
@JoostvDoorn Do you think you could also make a PR to add SeqGRU here? Would really appreciate.

**Comment by JoostvDoorn** [comment]
@nicholas-leonard Sure, unless @guillitte would want to do it here. I will have a look at this in a few days.

**Comment by nicholas-leonard** [comment]
@JoostvDoorn Thanks!

**Comment by MultiPath** [comment]
Thank you the kind attention of you all. Maybe it should be another issue. I am also wondering if and how we can use MaskZero for SeqLSTM. It doesn't seems to work by using :maskZero() or nn.MaskZero()? Pardon me for my question.

**Comment by nicholas-leonard** [comment]
@MultiPath I just opened a Pull Request (#242) to add support for maskzero to SeqLSTM.

**Comment by nicholas-leonard** [comment]
@JoostvDoorn How is the SeqGRU development coming?

**Comment by JoostvDoorn** [comment]
In progress, see 77ccbf3d777f03c7d981bb8a5425d201c6de5952
