### ISSUE TITLE
Adding minimalistic examples

### ISSUE THREAD

**Issue by peterroelants** [Element-Research/rnn#24]
This is not a bug issues, but it would be interesting to have a few minimalistic working toy examples on the usage with and without Sequencer .

**Comment by nicholas-leonard** [comment]
Hi I made a simpler example for RNN/LSTM : https://github.com/Element-Research/rnn/blob/master/examples/recurrent-language-model.lua . 

Also, I added a minimalist pseudo-equivalent of the example in the doc here : https://github.com/Element-Research/rnn#decorate-it-with-a-sequencer.

Please advise if this is still insufficient.
