### ISSUE TITLE
nn.MaskZero with Convolutions 

### ISSUE THREAD

**Issue by RicherMans** [Element-Research/rnn#248]
So I am still struggling with an issue regarding convolutions, which is more or less similar to the one I already discussed. #226 

My final goal is to use a CLDNN, a model which has a convolutional front end plus an RNN memory and finally a fully connected output. So far so good, but after training many models, I figured that my main problem are the zero paddings which I am doing. 

To simplify the overall problem, I the following code has a 5d input, which is `SEQLEN X BATCH X FEATMAPS X HEIGHT X WIDTH`. I want to pad my tensors in so that either some parts of the WIDTH tensor is set to zero or that a full sequence is set to zero. 
```lua
require 'rnn'
require 'nn'

mdl = nn.Sequential()

mdl:add(nn.SplitTable(1))
mdl:add(nn.Sequencer(nn.View(10)))
mdl:add(nn.SelectTable(-1))
mdl:add(nn.View(10))
mdl:add(nn.Identity())

mask = nn.MaskZero(mdl,4)
-- SEQLEN X BATCH X FEATMAPS X HEIGHT X WIDTH
vec = torch.Tensor(5,2,1,1,10):fill(1)
vec[{{},{1},{},{},{1,5}}]:zero()
vec[{{},{2},{},{},{5,7}}]:zero()

print(mask:forward(vec))
```

This will print the expected output of:
```
 0  0  0  0  0  1  1  1  1  1
 1  1  1  1  0  0  0  1  1  1
[torch.DoubleTensor of size 2x10]
```

But if I right now change the model using an appropriate Convolution Layer instead of the nn.View() ( which does not change the dimensionality of the input ) e.g.:

```lua
mdl:add(nn.SplitTable(1))
mdl:add(nn.Sequencer(nn.SpatialConvolution(1,1,1,1)))
mdl:add(nn.SelectTable(-1))
mdl:add(nn.View(10))
mdl:add(nn.Identity())
```

The output will result to some vector which does not contain any zeros e.g.:

```
 0.3830  0.3830  0.3830  0.3830  0.3830 -0.0887 -0.0887 -0.0887 -0.0887 -0.0887
-0.0887 -0.0887 -0.0887 -0.0887  0.3830  0.3830  0.3830 -0.0887 -0.0887 -0.0887
[torch.DoubleTensor of size 2x10]
```

I'm a bit confused why this happens. Could somebody explain?

**Comment by nicholas-leonard** [comment]
@RicherMans MaskZero looks for tensors of zero norm in the first dimension of its input. In your case, the masking never kicks in because it never detects the zero-norm tensors in the first dimension. If you wanted to do that you would need to apply the mask inside the sequencer and zero the entire tensor associated to sample i in batch and time-step t in sequence. For example : 
```lua
vec = torch.Tensor(5,2,1,1,10):fill(1)
local t, i = 3, 2
-- zero sample i at time-step t 
vec[{t,i,{},{},{}}] = 0
mdl = nn.Sequential()

mdl:add(nn.SplitTable(1))
mdl:add(nn.Sequencer(nn.MaskZero(nn.SpatialConvolution(1,1,1,1), 3)))
mdl:add(nn.SelectTable(t)) -- select time-step t
mdl:add(nn.View(10))
mdl:add(nn.Identity())

print(mdl:forward(vec))
```
Output:
```lua
-0.8275 -0.8275 -0.8275 -0.8275 -0.8275 -1.0820 -1.0820 -1.0820 -1.0820 -1.0820
-1.0820 -1.0820 -1.0820 -1.0820 -0.8275 -0.8275 -0.8275 -1.0820 -1.0820 -1.0820
[torch.DoubleTensor of size 2x10]

 1.3018  1.3018  1.3018  1.3018  1.3018  1.3018  1.3018  1.3018  1.3018  1.3018
 0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000
[torch.DoubleTensor of size 2x10]
```
