### ISSUE TITLE
Adding multiple skip connections

### ISSUE THREAD

**Issue by 0entr0py** [Element-Research/rnn#249]
I am trying to create RNNs where each node has (possibly multiple) skip connections to nodes multiple time steps apart . Could someone explain how I can modify the computation of the hidden state (h_t) to take into account all previous hidden states multiplied by a suitable sparse vector ?

Thanks

**Comment by nicholas-leonard** [comment]
@akshay13ml That is a bit complicated to implement. You might be able to do something like that by nesting RNNs. Here is an example : https://github.com/Element-Research/rnn/issues/229 (although not exactly what you want). Another possibility is to build your own module. To do this for LSTMs, I would recommend starting from SeqLSTM, subclassing and modifying it to suit your needs. It all depends on what exactly you want to do as some use-cases could be built as a Module outsize the LSTM (like NormStabilizer which is applied between LSTMs in a stack).
