### ISSUE TITLE
Norm stabilizer in evaluate mode

### ISSUE THREAD

**Issue by jrbtaylor** [Element-Research/rnn#256]
I'm using the norm stabilizer between two RNNs. The whole thing is wrapped in a sequencer. Training runs fine. When I set the model to evaluate for validation, I get the following error:

.../Torch/install/share/lua/5.1/rnn/NormStabilizer.lua:89: bad argument #1 to 'resizeAs' (torch.CudaTensor expected, got userdata)
stack traceback:
        [C]: in function 'resizeAs'
        .../Torch/install/share/lua/5.1/rnn/NormStabilizer.lua:89: in function '_updateGradInput'
        ...or/Torch/install/share/lua/5.1/rnn/AbstractRecurrent.lua:58: in function <...or/Torch/install/share/lua/5.1/rnn/AbstractRecurrent.lua:53>

It appears to make it part way through the sequence before the error comes up. Any ideas?

**Comment by jrbtaylor** [comment]
Nevermind, my mistake. I was running multi-threaded training but forgot to synchronize at the end of the training epoch, so some threads started validating before others finished training - the model was switched to evaluate mode before another thread tried to backprop.

**Comment by nicholas-leonard** [comment]
Glad you were able to solve this :)
