### ISSUE TITLE
Encoder-Decoder example returns error

### ISSUE THREAD

**Issue by satwikkottursc** [Element-Research/rnn#267]
The example about encoder-decoder-coupling throws error because of Select [here](https://github.com/Element-Research/rnn/blob/master/examples/encoder-decoder-coupling.lua#L60).

Is it to select the outputs at the last time step ?

**Comment by JoostvDoorn** [comment]
You should update the nn package, negative Select was only recently added.

**Comment by satwikkottursc** [comment]
Thank you, fixes it.
