### ISSUE TITLE
Inconsistency behavior of the Sequencer module

### ISSUE THREAD

**Issue by einatkermany** [Element-Research/rnn#27]
Hi,
In our model there is a Sequencer with dropout module. 
In the testing phase we call model:evaluate() but in the Sequencer the field sharedClones is not updated well - the field train is false only in the first module of sharedClones and in the rest of the module the train field remains true. The result is that the dropout module has its training behavior instead of testing behavior.
Could you please check it out?
Many thanks for your help, 
Einat

**Comment by nicholas-leonard** [comment]
Wow. I think you have just found a bug that was haunting me for the past weeks. Thanks. Should be fixed by https://github.com/Element-Research/rnn/commit/9ac37755dd2419abf0e1848d9fc2b02aba2073d7 .

Thanks @einatkermany !
