### ISSUE TITLE
handling inputSize > 1 for RNN (variable length sequence)?

### ISSUE THREAD

**Issue by zhouyong64** [Element-Research/rnn#272]
Hi, I'm working on a task where the feature size of one time step is 9 instead of 1, as is the case of char level language model. However, all of examples I can find of RNN (variable length sequence) is about language modeling.  Could you give me some pointers as to how to do that? Thanks very much.

**Comment by nicholas-leonard** [comment]
@zhouyong64 The [multivariate time series example](https://github.com/Element-Research/rnn/blob/master/examples/recurrent-time-series.lua) has multiple inputs. Check it out :)
