### ISSUE TITLE
Sequencer with variable length sequences

### ISSUE THREAD

**Issue by achalddave** [Element-Research/rnn#274]
It seems that it should be possible to use nn.Sequencer with variable length sequences. If I have a batch size of 2, and three sequences A (of length 2), B (of length 3), C (of length 5), I want to be able to do something like the following:

```lua
forward({A1, C1})
-- backward
forward({A2, C2})
-- backward
-- forget hidden states for A sequence
forward({B1, C3})
forward({B2, C4})
forward({B3, C5})
```

This could allow variable length sequences without padding. However, it seems there isn't a way to call `forget` for a particular set of sequences in the batch. It seems to me that I could do this by manually resetting internal variables like self.output, but perhaps I'm not sure if I'm missing some key issue that might make this tricky, or if there is an easier way to do this.

**Comment by nicholas-leonard** [comment]
@achalddave This is not how the Sequencer works. Each element in the table indexes time, not the batch. Your input is of shape batchsize x seqlen x inputsize while the correct shape is seqlen x batchsize x inputsize.

For variable length sequences, you can use [zero-masking](https://github.com/Element-Research/rnn#maskzeroninputdim)

**Comment by achalddave** [comment]
Oops; I was under the misconception that zero-masking required that short sequences be padded with zeros *until the end of the longest sequence*. I just realized that zero-masking also lets you delimit sequences:
> When a sample time-step is masked (i.e. input is a row of zeros), then the hidden state is effectively reset (i.e. forgotten) for the next non-mask time-step. In other words, it is possible seperate unrelated sequences with a masked element.

(My question was essentially whether it was possible to reset hidden states for certain sequences - apologies for not thoroughly reading the documentation!)

**Comment by nicholas-leonard** [comment]
@achalddave No worries :)
