### ISSUE TITLE
Optional Projection layer for SeqLSTM

### ISSUE THREAD

**Issue by nicholas-leonard** [Element-Research/rnn#281]
Hi @jnhwkim @JoostvDoorn @jcjohnson.

I wonder how hard it would be to modify the SeqLSTM to allow for a projection layer as specified in [LSTMP](http://static.googleusercontent.com/media/research.google.com/en//pubs/archive/43905.pdf). 

So this is the code for SeqLSTM and FastLSTM:
```lua
i[t] = σ(W[x->i]x[t] + W[h->i]h[t−1] + b[1->i])                      (1)
f[t] = σ(W[x->f]x[t] + W[h->f]h[t−1] + b[1->f])                      (2)
z[t] = tanh(W[x->c]x[t] + W[h->c]h[t−1] + b[1->c])                   (3)
c[t] = f[t]c[t−1] + i[t]z[t]                                         (4)
o[t] = σ(W[x->o]x[t] + W[h->o]h[t−1] + b[1->o])                      (5)
h[t] = o[t]tanh(c[t])                                                (6)      
```

Reading the paper, I think the LSTMP version of that would be:

```lua
i[t] = σ(W[x->i]x[t] + W[r->i]r[t−1] + b[1->i])                      (1)
f[t] = σ(W[x->f]x[t] + W[r->f]r[t−1] + b[1->f])                      (2)
z[t] = tanh(W[x->c]x[t] + W[h->c]r[t−1] + b[1->c])                   (3)
c[t] = f[t]c[t−1] + i[t]z[t]                                         (4)
o[t] = σ(W[x->o]x[t] + W[r->o]r[t−1] + b[1->o])                      (5)
h[t] = o[t]tanh(c[t])                                                (6)
r[t] = W[h->r]h[t]                                                   (7)
```

So basically, the size of `r[t]` and `x[t]` could be much smaller than the size of the cell `c[t]` and various gates: `f[t]`, `i[t]`, `o[t]` and `h[t]`.

The idea would be to modify SeqLSTM to take an optional 3rd argument:

```lua
lstm = nn.SeqLSTM(inputsize, hiddensize, [outputsize])
```

When the 3rd argument is provided, SeqLSTM internally implements LSTMP.

Does this make sense to you guys?

**Comment by jcjohnson** [comment]
I don't think that this is necessary; unless I've misunderstood I think you get the same behavior by adding a linear projection after an LSTM layer like this:

```lua
local net = nn.Sequential()
net:add(nn.SeqLSTM(I, H))
net:add(nn.TemporalAdapter(nn.Linear(H, O)))
```

(where `TemporalAdapter` internally combines the time and minibatch dimension before applying the wrapped module so you can apply the same function at each point in time and to each minibatch element)

**Comment by nicholas-leonard** [comment]
@jcjohnson Yeah I was thinking that it would be that simple. And the paper is a little convoluted about the LSTMP implementation. But if I understand it correctly, its more like feeding the output of the `TemporalAdapter(Linear)` back into the LSTM as the hidden state `h[t-1]`.

(I think TemporalAdapter and Sequencer are functionally equivalent)

**Comment by jcjohnson** [comment]
I see - I think you're right, they are feeding the projected vector from time T back into the model as the "previous hidden state" at time T+1. You can't implement that with a Sequencer / TemporalAdapter; you need to modify the SeqLSTM.

I don't think it would be too hard to modify SeqLSTM to add this option, but it would either result in a lot of code duplication (copy to SeqLSTMP.lua and make changes?) or several additional code paths in SeqLSTM.lua that would make it more complicated than it already is. I'm not sure if there's a clean and nice way to do it.

**Comment by nicholas-leonard** [comment]
@jcjohnson Yeah that is my fear...

**Comment by JoostvDoorn** [comment]
It seems doable if we implement SeqLSTM as a SeqLSTMP where `hiddensize == outsize`, and add a function `self:adapter()` on line [248](https://github.com/Element-Research/rnn/blob/3109cc9cbc01dab697772f044e5ac3d1c22f4cf0/SeqLSTM.lua#L248), which does `r[t] = W[h->r]h[t]` for SeqLSTMP, and `r[t] = h[t]` for SeqLSTM (+ same for `backward`). Then we have two modules one for `SeqLSTMP(inputsize, hiddensize, outputsize)`, and one for `SeqLSTM(inputsize, hiddensize)`. Which both implement a different adapter.

**Comment by nicholas-leonard** [comment]
@JoostvDoorn So basically, the SeqLSTMP would sub-class SeqLSTM but implement the adapter method?

**Comment by JoostvDoorn** [comment]
Yes exactly, unless I missed something in the paper.

**Comment by nicholas-leonard** [comment]
@JoostvDoorn Do you want to work on it? Otherwise I can find the time :)

**Comment by JoostvDoorn** [comment]
@nicholas-leonard Sure, I can give a crack at it this week.

**Comment by nicholas-leonard** [comment]
@JoostvDoorn Did you crack it?

**Comment by JoostvDoorn** [comment]
I got started I will make a pull request to track progress.

**Comment by nicholas-leonard** [comment]
@JoostvDoorn Looking good :+1:

**Comment by nicholas-leonard** [comment]
https://github.com/Element-Research/rnn#rnn.SeqLSTMP
