### ISSUE TITLE
Remember with fixed memory size

### ISSUE THREAD

**Issue by pefi9** [Element-Research/rnn#282]
Hi,

I would like to ask what would be the best way to implement following:
Training over very long sequence with high value for rho, e.g. sequence length 10^6 and rho 1000.
In other words, I would like to make the model to remember previous steps (so I don't have to forward input of length 1000 into model with `nn.SelectTable(-1)` - it`s very slow) but only rho previous steps - restricted memory. 

I have hypothesis that the value of a time series t_1+100 depends on sequence from interval {t_1 - 1000, t_1} not on the whole previous sequence {t_0, t_1}.

Thanks,
Petr

**Comment by nicholas-leonard** [comment]
rho is used for backpropagation. And SelectTable with a seqlen of 1000 will be difficult. t_1000 will be difficult to associated to t_0. In any case, I am not sure I understand what you mean to do.

**Comment by pefi9** [comment]
I know but rho is overridden by the sequence length, isn't it? However I might have wrongly understood the remember method for training. What I meant e.g. for sequence {h,e,l,l,o} with rho = 3, I would fw pass { h,e,l }, predict "L" and do bw prop. through time. Next I would not present the whole rho-long sequence on input, but just 'L' (the rest 'E, L' would network remembers), predict 'O' and the bw prop. through time over rho steps. That's what I thought the remember('train') means. 

I prepared some dummy example to test which value of rho can the model still handle - random sequence of int (1-10) with label_t_i = seq_t_(i - rho) + seq_t_i 
With single recurrent, lstm layer I was able to successfully train only with rho 10, or 15.

**Comment by nicholas-leonard** [comment]
It doesn't remember E L, per say. It simply remembers the previous hidden state h[t-1], (which H E L generated). Typically, if you are using Sequencer(rnn), use remember('both') for LSTMs and remember('eval') for RNNs. Control the rho by feeding shorter or longer sequence chunks to the Sequencer. Typically, longer sequences will take more examples to converge (so training will be slower) and use more memory, but they will also be able to learn longer-term dependencies (as compared to shorter sequences).

**Comment by pefi9** [comment]
Thanks for your reply.
