### ISSUE TITLE
SeqReverseSequence doesn't work after tensor conversion

### ISSUE THREAD

**Issue by genixpro** [Element-Research/rnn#286]
I'm using SeqReverseSequence. I train my model on a GPU, and then when saving the model, I convert all OpenCL tensors to regular double tensors.

However, SeqReverseSequence has two fields, self.outputIndices and self.gradIndices, which can't be convertted into a DoubleTensor. These fields work fine as CLTensors, but when working on a CPU, they must be LongTensor, otherwise I get an invalid tensor type on:
```
    self.output:gather(input, 1, self.outputIndices)
```

This function expects self.outputIndices to be a LongTensor when its actually just another DoubleTensor because the model has been converted, saved to a file and loaded again.

So far, I've been simply modifying my the SeqReverseSequence code to look like this:
```
    self.output:gather(input, 1, self.outputIndices:long())
```

And this magically works. But is there another way?

**Comment by nicholas-leonard** [comment]
Good catch :+1:  I think commit https://github.com/Element-Research/rnn/commit/27c7788ce583c1bc0d311529bce4473f49f70f25 should solve it. Let me know otherwise :)

**Comment by genixpro** [comment]
Thanks Nicholas for this prompt fix
