### ISSUE TITLE
Memory issue with RNN package and nn.SpatialMaxUnpooling

### ISSUE THREAD

**Issue by Somahtr** [Element-Research/rnn#287]
Hi there!

I'm currently encountered a problem whereby my GPU memory blows up when calling clearState on a nn.SpatialMaxUnpooling module inside a nn.Recursor. The following code should illustrate the issue:
```lua
require 'cunn'
require 'rnn'

-- Build model
local pool = nn.SpatialMaxPooling(2, 2)
local model = nn.Recursor(nn.Sequential()
    :add(pool):add(nn.SpatialMaxUnpooling(pool)))
model:cuda()

for i = 1, 10 do

    collectgarbage()
    model:forget()

    -- Run model forwards over sequence
    for t = 1, 10 do
        local input = torch.rand(1, 64, 224, 224):cuda()
        model:forward(input)
    end

    -- Print memory usage
    local freeMem, totMem = cutorch.getMemoryUsage()
    print(string.format('Iteration %i: %.4fGB', i, (totMem-freeMem)/1e9))

    -- Clear state
    model:clearState()
end
```

This script reports a rapid increase in memory usage:
```
Iteration 1: 0.3931GB	
Iteration 2: 0.4868GB	
Iteration 3: 0.4682GB	
Iteration 4: 0.5266GB	
Iteration 5: 0.5723GB	
Iteration 6: 0.5537GB	
Iteration 7: 0.5993GB	
Iteration 8: 0.6449GB	
Iteration 9: 0.6905GB	
Iteration 10: 0.7361GB
```
However if the clearState line is commented out, the memory usage remains stable:
```
Iteration 1: 0.3931GB	
Iteration 2: 0.4059GB	
Iteration 3: 0.4059GB	
Iteration 4: 0.4059GB	
Iteration 5: 0.4059GB	
Iteration 6: 0.4059GB	
Iteration 7: 0.4059GB	
Iteration 8: 0.4059GB	
Iteration 9: 0.4059GB	
Iteration 10: 0.4059GB	
```
This only occurs for SpatialMaxUnpooling and doesn't happen if the recursor is removed, so I think the issue must be something to do with the step cloning. MaxUnpooling saves a reference to the pooling module so maybe this is preventing previous steps from being garbage collected correctly? Please let me know if you have any thoughts or workarounds.

Many thanks!

**Comment by nicholas-leonard** [comment]
@Somahtr Sorry about the delay. Took me a while to find the bug. Fixed in https://github.com/Element-Research/rnn/commit/9656a155329071f5e7a6a98cb541828deddd618f . Thanks a million for taking the time to identify this bug :)

**Comment by Somahtr** [comment]
Many thanks @nicholas-leonard!!!
