### ISSUE TITLE
examples/noise-contrastive-estimate.lua 

### ISSUE THREAD

**Issue by parthaca** [Element-Research/rnn#288]
When I run
th noise-contrastive-estimate.lua --tiny
I get an error shown below in the NCEModule.lua. It looks like the problem might be in the loadGBW function in dataload. Should line loadGBW.lua:101
      local data = torch.Tensor(raw:size(1)+nsentence)
actually be
      local data = torch.LongTensor(raw:size(1)+nsentence)

I am new to Torch and it is possible that I haven't set default tensor type correctly or something like that.

Thanks for any suggestions.

------------------------
nn.Sequential {
  [input -> (1) -> (2) -> (3) -> output]
  (1): nn.ParallelTable {
    input
      |`-> (1): nn.Sequential {
      |      [input -> (1) -> (2) -> (3) -> (4) -> output]
      |      (1): nn.LookupTableMaskZero
      |      (2): nn.SeqLSTM
      |      (3): nn.SeqLSTM
      |      (4): nn.SplitTable
      |    }
      |`-> (2): nn.Identity
       ... -> output
  }
  (2): nn.ZipTable
  (3): nn.Sequencer @ nn.Recursor @ nn.MaskZero @ nn.NCEModule(200 -> 793471)
}
	
Epoch #1 :	
/home/test/torch/install/bin/lua: /home/test/torch/install/share/lua/5.2/nn/Container.lua:67: 
In 3 module of nn.Sequential:
...e/test/torch/install/share/lua/5.2/dpnn/NCEModule.lua:106: bad argument #3 to 'index' (torch.LongTensor expected, got torch.DoubleTensor)
stack traceback:
	[C]: in function 'index'
	...e/test/torch/install/share/lua/5.2/dpnn/NCEModule.lua:106: in function 'updateOutput'
	/home/test/torch/install/share/lua/5.2/rnn/MaskZero.lua:75: in function 'updateOutput'
	/home/test/torch/install/share/lua/5.2/rnn/Recursor.lua:25: in function 'updateOutput'
	/home/test/torch/install/share/lua/5.2/rnn/Sequencer.lua:58: in function </home/test/torch/install/share/lua/5.2/rnn/Sequencer.lua:39>
	[C]: in function 'xpcall'
	/home/test/torch/install/share/lua/5.2/nn/Container.lua:63: in function 'rethrowErrors'
	/home/test/torch/install/share/lua/5.2/nn/Sequential.lua:44: in function </home/test/torch/install/share/lua/5.2/nn/Sequential.lua:41>
	(...tail calls...)
	noise-contrastive-estimate.lua:223: in main chunk
	[C]: in function 'dofile'
	...test/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: in ?

**Comment by nicholas-leonard** [comment]
@parthaca Oh sorry. I never test without the --cuda flag. Fixed in https://github.com/Element-Research/dataload/commit/ec70382931d150384d6f5340e1d7e110ca6419f4 . Thank you for letting me know :)
