### ISSUE TITLE
Loading model issues in Recurrent Attention Model

### ISSUE THREAD

**Issue by yenchenlin** [Element-Research/rnn#290]
Hello, I'm using this [training script](https://github.com/Element-Research/rnn/blob/master/examples/recurrent-visual-attention.lua) trying to reproduce the result presented in this [great blog post](http://torch.ch/blog/2015/09/21/rmva.html#rmva.ref).

After running 500+ epoch, I accidently use ctrl+z to cut off the training process. I try to load the saved model and keep training, so I type the saved model's path into the arguments of the script.
```
cmd:option('--xpPath', '../save/jordan-All-Series:1468177316:1.dat', 'path to a previously saved model')
```

However, it fails to load the model and keep training, instead, it outputs the following error:
```
lua/5.1/nn/Sequential.lua:50>
        ...
        /home/yclin/torch/install/share/lua/5.1/dpnn/Decorator.lua:16: in function 'updateGradInput'
        /home/yclin/torch/install/share/lua/5.1/nn/Module.lua:31: in function 'backward'
        .../torch/install/share/lua/5.1/dp/propagator/optimizer.lua:72: in function 'backward'
        .../torch/install/share/lua/5.1/dp/propagator/optimizer.lua:52: in function 'propagateBatch'
        ...torch/install/share/lua/5.1/dp/propagator/propagator.lua:127: in function 'propagateEpoch'
        ...torch/install/share/lua/5.1/dp/propagator/experiment.lua:110: in function 'run'
        recurrent-visual-attention.lua:97: in main chunk
        [C]: in function 'dofile'
        ...clin/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00406670
```
On the other hand, I can use the same approach to evaluate the model using this [evaluation script](https://github.com/Element-Research/rnn/blob/master/scripts/evaluate-rva.lua) provided in the blog post, and it works pretty well.

Do I miss anything?

**Comment by nicholas-leonard** [comment]
@yenchenlin I am trying to move away from dp ( I don't have time to support it and its convoluted). This problem seems to be located in dp so I just removed the xpPath option.  Sorry this doesn't fix your issue. You could however modify the script to load the experiment, retrieve the underlying xp:model() and use that to initialize a new experiment. The saved hyper-parameters can be set using `opt = xp.opt`. Feel free to send a PR if you get it working.
