### ISSUE TITLE
what is the advantage of using LinearNB over Linear with bias in LSTM for input-to-hidden unit maps?

### ISSUE THREAD

**Issue by eriche2016** [Element-Research/rnn#297]
can you give some explainations or some reference. thanks

**Comment by eriche2016** [comment]
I kind of know the difference, is it try to avoid the 'double' biases term. for example, when summation of two linear layer outputs will cause two biases term here, this kinda violate the equation of RNN or LSTM. am i correct?

**Comment by nicholas-leonard** [comment]
@eriche2016 Yes, exactly.
