### ISSUE TITLE
recurrent-visual-attention.lua issue

### ISSUE THREAD

**Issue by northeastsquare** [Element-Research/rnn#30]
Hello, thank you for great project!
After I  trained a model using recurrent-visual-attention.lua , 
1. How do I use the model to get a picture's visual attention?
2. When I ran:
 th recurrent-visual-attention.lua --cuda --xpPath /home/silva/save/silva-XPS-8300\:1441270258\:1.dat
 I got the following error:
/home/silva/torch/install/bin/luajit: /home/silva/torch/install/share/lua/5.1/torch/File.lua:262: unknown Torch class <optim.ConfusionMatrix>
stack traceback:
	[C]: in function 'error'
/home/silva/torch/install/bin/luajit: /home/silva/torch/install/share/lua/5.1/torch/File.lua:262: unknown Torch class <optim.ConfusionMatrix>

**Comment by northeastsquare** [comment]
This is caused by: torch.load(xpfile)
How to solve?

**Comment by nicholas-leonard** [comment]
This should be fixed in latest rnn version (re-install it). However, you won't be able to retrain existing saved models using xpPath. For loading the model, you can still use the logic used by xpPath (it was just missing a require 'optim')

**Comment by northeastsquare** [comment]
Thank you, require 'optim' fix it. But how can I use the trained module to get a picture's visual attention?
