### ISSUE TITLE
LSTM Dropout

### ISSUE THREAD

**Issue by joeyhng** [Element-Research/rnn#301]
There are dropout options for GRU but not for LSTM/FastLSTM. I saw plots on the results of LSTM+Dropout in README, but could not figure out how to implement that. What is the right way to implement dropout for LSTM? Thanks.

**Comment by nicholas-leonard** [comment]
@joeyhng The best way is to insert dropout between the stacked LSTM layers : https://github.com/Element-Research/rnn/blob/master/examples/recurrent-language-model.lua#L108-L110.

**Comment by joeyhng** [comment]
Thanks. So actually the Dropout methods are different for LSTM and GRU on the plots in README.
