### ISSUE TITLE
Locator seems not work?

### ISSUE THREAD

**Issue by OptimusPrimeCao** [Element-Research/rnn#303]
hi,@nicholas-leonard 
I'm trying to train my own dataset using your recurrent-attention-model structure. The dataset has 28*28 size and contains formula characters like [0-9],[a-z],(,),-,+, etc. 
However, after 300 epoches, these are what I get:
![image](https://cloud.githubusercontent.com/assets/11535540/17075548/45784532-50c9-11e6-8670-6d506c5bd03a.png)
![image](https://cloud.githubusercontent.com/assets/11535540/17075549/4c51dff8-50c9-11e6-8fd8-8554dd1aee53.png)
![image](https://cloud.githubusercontent.com/assets/11535540/17075552/51f4d99c-50c9-11e6-8cdf-36db5b891040.png)
![glimpse_14](https://cloud.githubusercontent.com/assets/11535540/17075557/91251c26-50c9-11e6-9a7d-c6417a751272.png)
![image](https://cloud.githubusercontent.com/assets/11535540/17075553/59f23ec8-50c9-11e6-838e-e6d4a7f689db.png)
![image](https://cloud.githubusercontent.com/assets/11535540/17075556/75711214-50c9-11e6-8851-5f7bebbca0ab.png)

For all characters, after 2 steps or so, the locator always go to corner and stop predicting new glimpse locations.It seems that the locator dosen't work well. Is there something I should change with respect to your RAM structure?

What should I do in this particular case? Any suggestions? Thank you

**Comment by nicholas-leonard** [comment]
Hi, your `glimpseSize` seems really small. This is what I used to train the recurrent attention model on MNIST which is also 28x28:

```
th scripts/rnn-visual-attention.lua --cuda --useDevice 2 --rho 7 --rewardScale 1 --maxEpoch 2000 --maxTries 200 --learningRate 0.01 --sensorDepth 1 --momentum 0.9 --maxOutNorm -1 --batchSize 20 --saturateEpoch 800 --locatorStd 0.11 --uniform 0.1 --hiddenSize '{256}' --unitPixels 13 --glimpsePatchSize 8
```

The `unitPixels` argument is important as it prevents the model from getting stuck at the borders and corners.

**Comment by OptimusPrimeCao** [comment]
Thank for your reply! Do u think a glimpse with 2scale may work better in this case? or just a glimpse with 1scale, but a larger size?

**Comment by nicholas-leonard** [comment]
@OptimusPrimeCao Since your problem is so similar to MNIST, I would use exactly:
```
th scripts/rnn-visual-attention.lua --cuda --useDevice 2 --rho 7 --rewardScale 1 --maxEpoch 2000 --maxTries 200 --learningRate 0.01 --sensorDepth 1 --momentum 0.9 --maxOutNorm -1 --batchSize 20 --saturateEpoch 800 --locatorStd 0.11 --uniform 0.1 --hiddenSize '{256}' --unitPixels 13 --glimpsePatchSize 8
```

So a glimpse depth of 1 and a size of 8 pixels.

**Comment by milkfish1988** [comment]
I would like to ask how to get the output location of the locator when doing evaluation? How to write the code? Thanks!
