### ISSUE TITLE
Implementation Request : On Multiplicative Integration with Recurrent Neural Networks

### ISSUE THREAD

**Issue by Kaixhin** [Element-Research/rnn#306]
[On Multiplicative Integration with Recurrent Neural Networks](https://arxiv.org/abs/1606.06630) shows a boost in performance with RNNs by replacing the (elementwise) addition of the input and previous hidden state with an elementwise multiplication (a.k.a. the Hadamard product).

Rather than introducing a MI-RNN, MI-LSTM, MI-GRU etc., adding an extra flag to each of the existing units would seem better for code-reuse?

**Comment by Kaixhin** [comment]
@nicholas-leonard No - I think this is best left to someone who's already familiar with the codebase (as opposed to a pure user, e.g. myself).

**Comment by nicholas-leonard** [comment]
@Kaixhin Sounds good. In any case, thanks for suggesting the addition. I believe @Manojelement wants to work on it.

**Comment by ahmedmagdiosman** [comment]
Hey guys, is there any update on this?
