### ISSUE TITLE
Recent updates to SeqLSTM break previously saved models

### ISSUE THREAD

**Issue by willfrey** [Element-Research/rnn#314]
The addition of `self.hiddensize` to `nn.SeqLSTM` breaks previously initialized models that were saved to disk. Specifically, it return

```
~/torch/install/share/lua/5.1/rnn/SeqLSTM.lua:202: bad argument #2 to 'resize' (number expected, got nil)
```

I _think_ that manually copying `self.outputsize` to `self.hiddensize` would fix this, probably using `model:findModules('nn.SeqLSTM')`.

Just a heads up!

**Comment by nicholas-leonard** [comment]
@willfrey I think the latest commit should make it backwards compatible. Let me know if I am wrong and thanks for submitting this bug :)
