### ISSUE TITLE
Custom sentences for noise-contrastive-estimate.lua

### ISSUE THREAD

**Issue by namp** [Element-Research/rnn#317]
How can the code be modified so as to load a custom set of sentences (like e.g. in char-rrn or torch-rnn), rather than the Google billion words (GBW) dataset?

**Comment by nicholas-leonard** [comment]
@namp The GBW dataset uses the [MultiSequence](https://github.com/Element-Research/dataload#dl.MultiSequence) loader. Just wrap your custom sequences in one of those.

**Comment by namp** [comment]
Thank you for your reply.

Perhaps I should had rephrased the question: What the custom corpus input format should be like (e.g. one sentence per line? would a file like [this](https://github.com/karpathy/char-rnn/blob/master/data/tinyshakespeare/input.txt) in do? ) 

billionwords.tar.gz contains already processed ".t7" files and it is not quite obvious.

Thanks again

**Comment by JoostvDoorn** [comment]
You will probably have to write some code for your specific dataset, MultiSequence takes a table of tensors. You can use util functions from dataload to make things easier, see [here](https://github.com/Element-Research/dataload/blob/master/utils.lua), specifically dl.buildVocab and dl.text2tensor should help.

**Comment by namp** [comment]
The link was really helpful - apologies for the question if the task is trivial. I've been working in python for nlp tasks and I'm not that familiar with Lua.

Many thanks
