### ISSUE TITLE
Sequence to Sequence model for language model

### ISSUE THREAD

**Issue by deathlee** [Element-Research/rnn#322]
Hi I am trying to implement a seq2seq model. There is no loss in the encoder part and only NCE loss in the decoder part. I am thinking using SelectTable(). If it is a many to one task I could only need to SelectTable(-1) as in your example. However the sentence length is not fixed so how could I make sure the sequence criterion won't receive the output of the encoder? Is there any way I could mask the output of encoder?

**Comment by nicholas-leonard** [comment]
use zero-padding before the input and `maskZero()` on your recurrent models. The twitter example is similar to your problem.
