### ISSUE TITLE
Error: Invalid arguments in VRClassReward.lua 

### ISSUE THREAD

**Issue by mobarakolislam** [Element-Research/rnn#325]
Hi,

I'm having this error for the recurrent-visual-attention.lua with CUDA. Can anyone help me please?

VRClassReward.lua:28: invalid arguments: CudaTensor CudaTensor CudaTensor number 
expected arguments: CudaTensor | [*CudaTensor*] [*CudaLongTensor*] CudaTensor index

Thanks

**Comment by guo2004131** [comment]
I have the same problem

**Comment by guo2004131** [comment]
Problem solved: 
Please reinstall "cutorch" using
luarocks install cutorch 1.0-0

**Comment by mobarakolislam** [comment]
wow..It works. Thanks @guo2004131

**Comment by guo2004131** [comment]
Alternatively, if you have already installed the latest cutorch, then you might want to replace the Line28 "self._maxVal:max(self._maxIdx, input, 2)" with "self._maxVal,self._maxIdx = torch.max(input,2)"

**Comment by nicholas-leonard** [comment]
@mobarakolislam @guo2004131 fixed in https://github.com/Element-Research/dpnn/commit/ead91a239317dfcc04a0291cfa719f5f3ce7b6ba . Thanks for identifying this issue!
