### ISSUE TITLE
LSTM implementation

### ISSUE THREAD

**Issue by bartvm** [Element-Research/rnn#34]
Question: Why does the LSTM implementation not inherit from `Recurrent`? I it seems that (something like) this is equivalent to the current LSTM implementation, but avoids a lot of code duplication.

```lua
nn = require 'nn'
require 'rnn'

local hiddenSize = 2
local nIndex = 2

-- A silly hack to make sure LSTM.recurrentModule is fed zeros at step 1
local Start = torch.class('nn.Start', 'nn.Identity')

function Start:updateOutput(input)
  self.output = {input, torch.zeros(2), torch.zeros(2)}
  return self.output
end

function Start:updateGradInput(input, gradOutput)
  self.gradInput = gradOutput[1]
  return self.gradInput
end

-- The LSTM network
-- The input and feedback modules are unused
-- Merge basically turns {input, {output, cell}} into {input, output, cell}
-- The transfer module is the full LSTM module
local r = nn.Recurrent(nn.Start(), nn.Identity(), nn.Identity(),
                       nn.LSTM(hiddenSize, hiddenSize).recurrentModule,
                       9999, nn.FlattenTable())

local rnn = nn.Sequential()
rnn:add(r)
rnn:add(nn.SelectTable(1))  -- Since both the output and the cell is given
rnn:add(nn.Linear(hiddenSize, nIndex))
rnn:add(nn.LogSoftMax())
```

**Comment by nicholas-leonard** [comment]
@bartvm I see what you mean. The above example makes sense except that the start module (first arg of Recurrent), would actually need to be something like this : 
```lua
local start = nn.Sequential()
start:add(nn.Start())
start:add(recurrentModule:sharedClone())
```

So why the separate implementation? By inheriting nn.Recurrent, you need to add nn.SelectTable(1) to limit access to the output (not the cell). I guess that was the main reason I made a separate implementation. The other reason being that lack of a nn.Start module.

**Comment by bartvm** [comment]
Why is the `sharedClone` needed? According to the documentation the `transfer` module (i.e. the module containing the LSTM unit) gets applied at the first step as well, after the `start` module. That would mean your suggestion would end up applying the LSTM unit twice, once as part of the `start` module and once as part of the `transfer` module (probably crashing, because the second LSTM module expects 3 inputs and would only get two).

**Comment by nicholas-leonard** [comment]
@bartvm Oh yeah. I wrongly understood you were doing something like this : 
```lua
nn.Recurrent(nn.Start(), nn.Identity(), nn.LSTM(hiddenSize, hiddenSize).recurrentModule,
                     nn.Identity(), 9999, nn.FlattenTable())
```
In that case, not need for the sharedClone.

**Comment by nicholas-leonard** [comment]
@bartvm if you like, you can submit a PR with an nn.FullLSTM that does that.
