### ISSUE TITLE
empty rockspec?

### ISSUE THREAD

**Issue by montyhall** [Element-Research/rnn#340]
Hi

 I pulled the latest rockspec file from the github repo and tried to install directly against that.

[root@admin ~]# luarocks install rnn-scm-1.rockspec
Cloning into 'rnn'...
...

The output indicates a successful installation.  But the files it says that it installed are not actually present:

...
-- Installing: /usr/local/pkg/LuaJIT/2.0.4/lib/luarocks/rocks/rnn/scm-1/lua/rnn/test/test.lua
-- Installing: /usr/local/pkg/LuaJIT/2.0.4/lib/luarocks/rocks/rnn/scm-1/lua/rnn/test/GRU_test.lua
-- Installing: /usr/local/pkg/LuaJIT/2.0.4/lib/luarocks/rocks/rnn/scm-1/lua/rnn/test/bigtest.lua
-- Installing: /usr/local/pkg/LuaJIT/2.0.4/lib/luarocks/rocks/rnn/scm-1/lua/rnn/test/test_trimzero.lua
rnn scm-1 is now installed in /usr/local/pkg/LuaJIT/2.0.4 (license: BSD)

But if you check for the existence of anything it said it installed, none of it is there:

[root@admin rnn]# ls -l /usr/local/pkg/LuaJIT/2.0.4/lib/luarocks/rocks/rnn/scm-1/lua/rnn/test/bigtest.lua
ls: cannot access /usr/local/pkg/LuaJIT/2.0.4/lib/luarocks/rocks/rnn/scm-1/lua/rnn/test/bigtest.lua: No such file or directory

It also lists "cunnx" as a dependency which is one we didn't have installed, yet I can't find anything on Google about this --- no github repo, no installation instructions, etc.  I went ahead and just blindly installed it using the general repo we used yesterday (https://raw.githubusercontent.com/torch/rocks/master).  After successful installation of cunnx, I tried to install rnn again, only to get the same results above.

Am I doing something wrong here?

**Comment by nicholas-leonard** [comment]
@montyhall Were you able to resolve this?

**Comment by montyhall** [comment]
even though the installation process was reporting that it was installing to a certain location, it actually installed to another location successfully.  Confusing.

i am still experiencing an error which according to issue 313 <https://github.com/Element-Research/rnn/issues/313> is cutorch breaks backward compatibility of rnn (in `MaskZero`). 


LuaJIT-2.0.4/share/lua/5.1/rnn/MaskZero.lua:76: invalid arguments: CudaByteTensor CudaTensor number 
expected arguments: [*CudaTensor*] CudaTensor float | [*CudaTensor*] CudaTensor CudaTensor
stack traceback:
	[C]: in function 'eq'
	/usr/local/stow/LuaJIT-2.0.4/share/lua/5.1/rnn/MaskZero.lua:76: in function 'updateOutput'
	/usr/local/stow/LuaJIT-2.0.4/share/lua/5.1/rnn/LSTM.lua:162: in function 'updateOutput'
	.../local/stow/LuaJIT-2.0.4/share/lua/5.1/rnn/Sequencer.lua:59: in function <.../local/stow/LuaJIT-2.0.4/share/lua/5.1/rnn/Sequencer.lua:40>
	[C]: in function 'xpcall'
	/usr/local/stow/LuaJIT-2.0.4/share/lua/5.1/nn/Container.lua:65: in function 'rethrowErrors'
	.../local/stow/LuaJIT-2.0.4/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	train.lua:103: in function 'gradientUpgrade'
	train.lua:184: in function 'main'
	train.lua:192: in main chunk
	[C]: in function 'dofile'
	.../stow/LuaJIT-2.0.4/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00404ac0

WARNING: If you see a stack trace below, it doesn't point to the place where this error occured. Please use only the one above.
stack traceback:
	[C]: in function 'error'
	/usr/local/stow/LuaJIT-2.0.4/share/lua/5.1/nn/Container.lua:69: in function 'rethrowErrors'
	.../local/stow/LuaJIT-2.0.4/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'


 bug was supposedly fixed here

https://github.com/Element-Research/rnn/pull/319 <https://github.com/Element-Research/rnn/pull/319>

with merged commit bbec157 <https://github.com/Element-Research/rnn/commit/bbec1572127c3deca45e8924e29d550934459eb2> into Element-Research:masteron August 9 in `rnn` package. 

installed rnn using

> luarocks install rnn-scm-1.rockspec

best

Peyman
