### ISSUE TITLE
how to forward a sequencer module step by step?  for sampling

### ISSUE THREAD

**Issue by Tae618** [Element-Research/rnn#352]
I have built a model as follows
```
function layer:buildLanguageModel()
  local dec = nn.Sequential()
  dec:add(nn.LookupTableMaskZero(self.vocabsize+1, self.hiddensize))
  dec.lstmLayers = {}
  for i=1, self.nlayer do  
      dec.lstmLayers[i] = nn.LSTM(self.hiddensize, self.hiddensize):maskZero(1)
      dec:add(nn.Sequencer(dec.lstmLayers[i]))
  end
  dec:add(nn.Sequencer(nn.MaskZero(nn.Linear(self.hiddensize, self.vocabsize+1), 1)))
  dec:add(nn.Sequencer(nn.MaskZero(nn.LogSoftMax(), 1)))
  
  return dec
end
```
In the training phase, it will use a sequence of words as input.
But in the evaluating phase, I use a start token as input for t=0 step forward and then the input of t step will be the output of t-1 step. So I need forward the sequencer module step by step from 1 to sequence length step.
Anyone knows how to do this ?

**Comment by Tae618** [comment]
I wonder if sequencer module can forward at single time-step. Maybe it must forward for sequence and can't forward a single step.

**Comment by JoostvDoorn** [comment]
You can use remember with Sequencer. You might find it helpful to have a look at #304 .

**Comment by Tae618** [comment]
Thank you for your suggestion, I have known how to deal with it.
Just like [#247](https://github.com/Element-Research/rnn/issues/247) does and making some changes will be ok.

**Comment by sudongqi** [comment]
The solution on #247 doesn't work for me. Maybe it's because I am using SeqLSTM and SeqLSTM handle forget and remember differently?
