### ISSUE TITLE
SeqGRU throws error

### ISSUE THREAD

**Issue by satwikkottur** [Element-Research/rnn#354]
SeqGRU throws the following error, while SeqLSTM runs without a problem. I am using the latest version of cutorch.

torch/install/share/lua/5.1/rnn/SeqGRU.lua:108: invalid arguments: CudaTensor CudaTensor number
expected arguments: *CudaTensor* CudaByteTensor float
stack traceback:
	[C]: in function 'maskedFill'

**Comment by JoostvDoorn** [comment]
Thanks for the report! I opened a pull request to fix this.
