### ISSUE TITLE
Is there any attention module that I could use for neural machine translation?

### ISSUE THREAD

**Issue by anoidgit** [Element-Research/rnn#359]
I find Recurrent Attention, but it seems  work for some other task?

**Comment by gaosh** [comment]
you can take a look at this post [https://chaonan99.github.io/2016/easy-explanation-to-temporal-attention/](url)

**Comment by gaosh** [comment]
you can take a look to this [post](https://chaonan99.github.io/2016/easy-explanation-to-temporal-attention/)

**Comment by anoidgit** [comment]
@gaosh Thank you, I think I can solve this now.
