### ISSUE TITLE
backward() vs backwardThroughTime()

### ISSUE THREAD

**Issue by davidBelanger** [Element-Research/rnn#36]
I'm confused about how to use this library in such a way that it is API-compatible with the rest of torch. For other parts of torch, eg for simple MLPs, it seems that the standard pattern for training models is to do something like:

local parameters, gradParameters = model:getParameters()
local inputs, targets = getMiniBatch()

local function fEval(x)
        if parameters ~= x then parameters:copy(x) end
        model:zeroGradParameters()
        local output = model:forward(inputs)
        local err = criterion:forward(output, targets)
        local df_do = criterion:backward(output, targets)
        model:backward(inputs, df_do) 
        return err, gradParameters
end

optim.optimMethod(fEval, parameters)

I'd like to be able to use this package's RNN code, but train using training code I already have.  However, it seems that backward() doesn't do something and we have to call backwardThroughTime() instead. 

1) Is this true? Why not make the RNN stuff API-compatible so that we can call backward()? 
2) If I'm going to add a backwardThroughTime() call to my training code? Where do I put it? Do I call backward() and then backwardThroughTime(). Suppose there are LookupTable layers below the RNN. After calling backwardThroughTime, would I need to call backward() on them?

Thanks,
David

**Comment by nicholas-leonard** [comment]
@davidBelanger 1. yes. However, if you want your rnn to be compatible with the optim API, you wrap it in a nn.Sequencer. The Sequencer takes care of the backwardThroughTime during its backward call.

2. if you don't want to wrap your rnn in a Sequencer, you will have to call backwardThroughTime after your sequence of inputs,targets has been fed in (forward/backwarded). Please refer to the [Recurrent doc examples](https://github.com/Element-Research/rnn#rnn.Recurrent) for additional details.

**Comment by davidBelanger** [comment]
Thanks! It sounds like Sequencer is exactly what I was looking for. My mistake was just to use the RNN and not wrap it in that. 
Cheers,
David
