### ISSUE TITLE
recursiveCopy got nil in recursiveUtils.lua

### ISSUE THREAD

**Issue by deepcoord** [Element-Research/rnn#386]
FastLSTM with MaskZero spit out nil error.

> /root/torch/install/bin/luajit: /root/torch/install/share/lua/5.1/rnn/recursiveUtils.lua:44: expecting nested tensors or tables. Got nil and nil instead

**Comment by aep** [comment]
@deepcoord how did you fix this?

**Comment by ganeshjawahar** [comment]
`--[[ Forward coupling: Copy encoder cell and output to decoder LSTM ]]--
function Seq2Seq:forwardConnect(inputSeqLen)
  self.decoderLSTM.userPrevOutput =
    nn.rnn.recursiveCopy(self.decoderLSTM.userPrevOutput, self.encoderLSTM.outputs[inputSeqLen])
  self.decoderLSTM.userPrevCell =
    nn.rnn.recursiveCopy(self.decoderLSTM.userPrevCell, self.encoderLSTM.cells[inputSeqLen])
end

--[[ Backward coupling: Copy decoder gradients to encoder LSTM ]]--
function Seq2Seq:backwardConnect(inputSeqLen)
  self.encoderLSTM:setGradHiddenState(inputSeqLen, self.decoderLSTM:getGradHiddenState(0))
end`

**Comment by longjiangxue** [comment]
@aep  @ganeshjawahar   Do your  solve this question?
