### ISSUE TITLE
WARNING : recurrentModule should be added to sharedClones in constructor. Adding it for you.

### ISSUE THREAD

**Issue by InnovArul** [Element-Research/rnn#388]
Hello, 

I have written a model using nn.GRU and a nn.Sequencer decorating the GRU for forwarding the video frames, that are organized as a table. During training, I am getting the following warning:

**WARNING : recurrentModule should be added to sharedClones in constructor.
Adding it for you.**

Also, the model doesn't seem to learn. Is there any relation between this warning and the model not-learning from data?

Could you please give any hint on possible causes?

**Comment by jnhwkim** [comment]
Can share the reproducible code?

**Comment by InnovArul** [comment]
Sorry. Changed the code so much that I could not reproduce it.
I will get back when I face this warning again.
