### ISSUE TITLE
Sharing params using clone() on Sequencer(LSTM())

### ISSUE THREAD

**Issue by karthikncode** [Element-Research/rnn#4]
Hi,
I have the following architecture:

        lstm_seq = nn.Sequential()
        lstm_seq:add(nn.Sequencer(l))
        lstm_seq:add(nn.SelectTable(args.state_dim))
        lstm_seq:add(nn.Linear(n_hid, n_hid))
        lstm_seq:add(nn.Rectifier())

        parallel_flows = nn.ParallelTable()
        for f=1, 2 do
            parallel_flows:add(lstm_seq:clone("weight","bias"))
        end

        lstm = nn.Sequential()
        lstm:add(parallel_flows)

If I check the parameters by using:

       w, dw = lstm.getParameters()

I get inconsistent sizes (dw seems to have almost twice the number of params as w).
However, when I turn off sharing params (in lstm_seq:clone()), the sizes are consistent. Do you have any idea why?

Thanks!

**Comment by nicholas-leonard** [comment]
Hi,

try `parallel_flows:add(lstm_seq:clone("weight","bias","gradWeight", "gradBias"))`.

**Comment by karthikncode** [comment]
Works great. Thanks!
