### ISSUE TITLE
save Model problem

### ISSUE THREAD

**Issue by xieshuqin** [Element-Research/rnn#409]
Hi 

I decorate a nngraph model with nn.Recursor to make it a nn.AbstractSequencer class. But when I try to save a train model, the following error raises:
 Unwritable object <function> at <?>.<?>.modules.1.<?>.rnn.test.rnntest.__tests.Sequencer._.__index.rejectWhile._.rejectWhile.ipairs

It's very weird because when I test the code on my laptop, it works. But when I run it on a server, it raise the above error when executing torch.save(). Note that I have another torch.save() in front of it, and that works just fine. So Is there any problem when decorating nngraph model with nn.Recursor ?

Thanks for your reply

**Comment by jnhwkim** [comment]
Have you tried to update related packages on the server?

**Comment by xieshuqin** [comment]
I update rnn but it doesn't work.
