### ISSUE TITLE
Question on memory usage for LSTM?

### ISSUE THREAD

**Issue by hsheil** [Element-Research/rnn#5]
Platform: OSX 10.10.3.
Revision: Reasonably current (17/5) git pull of Torch7 and rnn.
Runtime: CPU (not GPU - yet).

**Background**: I'm modelling events that happen over a 30-day window, with each window divided into 3 minute time-steps. So each distinct user has 30*24*(60/3)=14,400 events with a lot of these simply encoding the fact that nothing happened. I've got 60k users to look at initially and an 80:20 split between train and test, so 48k training users and 12k test users.

**Problem**: I inevitably run out of memory about 60 minutes after training - running into the 1 GB luajit cap. Adding collectgarbage() inside the forward / backward loop helped but only to delay the out of memory from 1 minute to 60 minutes. I'm using Tensors throughout my code, not tables.

**My planned solutions**: I'm working on restructuring my code to load the training data on the fly from storage and then using subsets of the data as mini-batches to hopefully remain within the 1 GB limit as well as evaluating more compressed / efficient ways of modelling the events themselves (but part of my research is to see how good LSTM is at extracting features from the events through time without having to preprocess those events..).

**Question**: Is this behaviour (exceeding the 1 GB luajit mem limit) simply expected behaviour in the current LSTM code for a dataset of this size - that it's using a table somewhere to maintain state (e.g. unrolling through time etc.) or is it more likely that there is a bug somewhere in my code manifesting itself as this problem and RNN / LSTM should have a stable / reasonable mem usage profile?

**Comment by nicholas-leonard** [comment]
If you are training the LSTM with very large sequences (1000+), then the memory limit could possibly be located in the LSTM code as it maintains a state (which is a table stored in a table) for each step. However, your sequence would have to be very large. If this is your case, then I suggest cutting the training problem into smaller sequences of say 100-500. 

For testing (i.e. with `lstm:evaluate()`), you could use the entire sequences without incurring any memory overhead (it only keeps track of the previous state). But this is only true when you use the nn.LSTM directly without nn.Sequencer.

Otherwise, your computer may be simply running out of memory. I have often seen people confuse the 1G luajit mem limit issue with just plain old not enough physical memory.

**Comment by hsheil** [comment]
Ok, thanks! I wrote my code around Sequencer first (and hit this problem) so switched over to nn.LSTM directly to see if I could get more control over what was happening. I'll play around with successively smaller sequence sizes and report back. I should have mentioned each event is modelled as a 33-bit vector so individually they are quite small, so that points to the sequence length.

RE: simply running out of memory, yes it could be this and will check this as well. As a (tenuous) sanity check I built the same model in keras / Theano and ran the same size dataset through it. It worked but was swapping very, very heavily on an 8 GB RAM machine.

**Comment by nicholas-leonard** [comment]
Keep me posted. Thanks.

**Comment by hsheil** [comment]
Hi - I propose closing this issue for now, at least until I can provide more debug details on exactly where the memory is going - all of the Torch LSTM impls exhibit the same performance for relatively large numbers of timesteps (Zaremba, Karpathy, rnn). Based on that, unrolling the network through time is an expensive operation in Torch the platform, not in rnn the impl..

For now I've gotten around it by moving the time dimensionality into the data layer which isn't ideal but works (memory-wise at least, still testing confusion matrix accuracy..).
