### ISSUE TITLE
testJacobian fails on Missing gradInput

### ISSUE THREAD

**Issue by vgire** [Element-Research/rnn#50]
When trying to test a simple network (to get the last state of an LSTM)
```lua
local sequenceLength = math.random(5, 10)
local vectorSize = math.random(5, 10)
local hiddenSize = math.random(5, 10)

local input = torch.rand(sequenceLength, vectorSize)

-- testJacobian doesn't support table inputs so use a split table module on the input.
local module = nn.Sequential()
module:add(nn.SplitTable(1, 2))
module:add(nn.Sequencer(nn.FastLSTM(vectorSize, hiddenSize)))
module:add(nn.SelectTable(-1))

nn.Jacobian.testJacobian(module, input)
```
`nn.Jacobian.testJacobian` fails at https://github.com/Element-Research/rnn/blob/master/AbstractRecurrent.lua#L61

Am I missing something ?
Can you provide a pointer to solve this ?

Thanks

**Comment by nicholas-leonard** [comment]
Yeah the AbstractRecurrent wont work with jacobian unit tests like that. This is because the test calls backward multiple times per forward, yet the rnn requires at most one backward per forward (because it keeps an internal time-step counter).
