### ISSUE TITLE
Implementing many-to-one RNN

### ISSUE THREAD

**Issue by nvram83** [Element-Research/rnn#51]
Hi,
Thanks for the great RNN package! I am trying to implement a many-to-one RNN, LSTM specifically, where each sequence of inputs only produces a single output and finding it difficult to use the rnn package for this case. This is useful for e.g. in sentiment analysis where each review (with a set of words) gets mapped to a sentiment (positive or negative).

Any help regarding this would be appreciated. I am not sure if I should have raised an issue for this since this is a personal question but hoping others would benefit too.

Thanks a lot for your help!

**Comment by nicholas-leonard** [comment]
Yeah it's actually pretty easy to do. 

```lua
mlp = nn.Sequential()
mlp:add(nn.Sequencer(nn.LSTM(100,100)))
mlp:add(nn.SelectTable(-1))
mlp:add(nn.Linear(100,10)
mlp:add(nn.LogSoftMax())
```
So the key is to use `SelectTable(-1)` to retrieve the last element of the sequence and feed into a classifier (or whatever you want).

**Comment by nvram83** [comment]
Thanks! That's exactly what I was looking for - the SelectTable() is the key here.

**Comment by shoaibahmed** [comment]
@nvram83 Can you pl upload the complete code?
