### ISSUE TITLE
Seems like opt.accUpdate in recurrent-language-model.lua is no longer used?

### ISSUE THREAD

**Issue by hughperkins** [Element-Research/rnn#52]
Seems like opt.accUpdate in recurrent-language-model.lua is no longer an available option, but still appears in the code?

```
lookup = nn.LookupTable(ds:vocabularySize(), opt.hiddenSize[1], opt.accUpdate)
```

```
   acc_update = opt.accUpdate,
```

**Comment by nicholas-leonard** [comment]
@hughperkins Yup those were left over from a previous version. Script updated https://github.com/Element-Research/rnn/blob/master/examples/recurrent-language-model.lua . Thank you for that!
