### ISSUE TITLE
Bug in new AbstractRecurrent? updateGradInputStep not reset

### ISSUE THREAD

**Issue by dirkweissenborn** [Element-Research/rnn#53]
in method updateGradInput, I find:
self.updateGradInputStep = self.updateGradInputStep or self.step

First BPP pass is fine. However, if I do a second BPP pass self.updateGradInputStep is initialized (it is 1 after the first BPP), and is decreased to negative values even. Shouldn't updateGradInputStep be reset at some point between BPP passes?

**Comment by nicholas-leonard** [comment]
@dirkweissenborn Yeah it is reset when a call to `updateOutput` is made. So you should call `updateOutput` for `rho` time-steps and then call `backward` (i.e. `updateGradInput` and `accGradParameters`) for `rho` timesteps in reverse order of the calls to `updateOutput`. So the last `input` to be forwarded through via `updateOutput` is the first to be backpropagated via `updateGradInput` and `accGradParameters`.

**Comment by dirkweissenborn** [comment]
@nicholas-leonard , thanks for clearing that up. I was deriving a new class from AbstractRecurrent and that is why I had to reset it manually. It wasn't clear from the documentation that it needed to be done. However, I know that for most usecases Recursor and Recurrence should be enough, where this is handled. Thanks again.
