### ISSUE TITLE
Adding Examples for Different RNN Structures

### ISSUE THREAD

**Issue by ssakhavi** [Element-Research/rnn#57]
Hi, 

I wanted to suggest adding examples for different architectures using Recurrent structures. 

For example:
![Link to the blog] (http://karpathy.github.io/assets/rnn/diags.jpeg)
Image [Link](http://karpathy.github.io/2015/05/21/rnn-effectiveness/).

I've seen that you've added some example in some of the issues (#51,#21).
Maybe adding them explicitly in the examples folder can reduce confusion. 

Siavash

**Comment by shoaibahmed** [comment]
This will certainly help the new starters a lot

**Comment by nicholas-leonard** [comment]
@ssakhavi Examples for most of these have been added to the examples folder. If you need more, please let me know.
