### ISSUE TITLE
time series prediction

### ISSUE THREAD

**Issue by andrewcz** [Element-Research/rnn#61]
hi all,
just wondering if this library can be used for either multivariate or univariate time series prediction.
Is there already an example of this?

Many thanks,
best,
Andrew

**Comment by rracinskij** [comment]
Hi, 
just trying to solve the same problem. Here are two links:
http://apaszke.github.io/lstm-explained.html (+comments)
https://github.com/DataToKnowledge/torch-lstm 
But I don't know yet how to adapt it for multivariate time series, so I'd also greatly appreciate any help.

Regards,
Richard

**Comment by nicholas-leonard** [comment]
@andrewcz The language model (LM) example if very simple to your time series prediction.

## Language Model
 * object is to predict the next word given the previous words.
 * input for each time-step is the index of a word : an scalar integer
 * output for each time-step is the likelihoods over all words : a vector of floats
 * if your task is to find the most likely sequence of words to follow a known sequence, then you can perform a beam search over all possible combinations, keeping only the most likely sequences.

## Time series 
 * object is to predict the value of the next step given the previous steps
 * input for each time-step is a univariate/multivariate value : a scalar or vector float/integer
 * output for each time-step is the prediction of the next value : same as input

If your task is to find the most likely sequence of predictions for time series, not sure how this is done. Just feeding the prediction of next value as input to the RNN for the next time step, will not necessarily guarantee this, but it is an acceptable approach. You can consult http://www.ulb.ac.be/di/map/gbonte/ftp/time_ser.pdf (forecasting section, slide 88 and up) to get an idea of the different way the model can be used for forecasting.  

In any case, we don't currently have examples of time-series prediction. But all the components should be there to build such a model and use it for forecasting.

**Comment by senecaur** [comment]
I am also trying to achieve something similar (classification of multivariate time series).  Can you clarify what the structure of a batch of input sequences should be?  For example, I have 28-dimensional time series each with 28 time-steps.  If I want to input these in batches of 64 should my input table contain a tensor of size 64x28x28 or of 1792x28?  Or something else? Thanks!

**Comment by rracinskij** [comment]
Hi, I tried to simplify the example provided in the description of the Recurrent module by changing the inputs and outputs to scalars. Maybe it will be helpful:

https://github.com/rracinskij/rnntest01/blob/master/rnntest01.lua

**Comment by andrewcz** [comment]
thanks rracinskij!!!
is this a multivariate version through a numerical array?
Many thanks,
Andrew

**Comment by rracinskij** [comment]
No, it is univariate, but it should be probably easy to modify it to use multivariate time series.

**Comment by nicholas-leonard** [comment]
Added link to your example @rracinskij https://github.com/Element-Research/rnn/blob/master/README.md . Thanks.

**Comment by rracinskij** [comment]
@andrewcz It looks like that building a model for a multivariate time series prediction is much trickier than it seemed at the beginning. A model should probably use a sequence of vectors as inputs and targets and it is quite unclear how to implement it.
Have you figured out something? Thank you.
