### ISSUE TITLE
Request for GRU implementation.

### ISSUE THREAD

**Issue by jnhwkim** [Element-Research/rnn#63]
GRU is an efficient model can be replaced with LSTM.

**Comment by nicholas-leonard** [comment]
@jnhwkim Would you like to implement it? We can help you polish and debug it.

**Comment by jnhwkim** [comment]
I can try only after this semester... anyway, thanks for encouraging me!

**Comment by hughperkins** [comment]
I might try this ... or I might just keep reading papers :-P  Who knows... either way, cant helping thinking that tasks such as this are perfect for all those questions on reddit , like "are there any opensource ml projects I can contribute to?", so I might go to the torch7 issues page, and file an idea that tasks such as this are added to some central list, for people to pickup and action.

**Comment by nicholas-leonard** [comment]
Done thanks to @jnhwkim !
