### ISSUE TITLE
Help understanding what encInSeq, decInSeq, decOutSeq are in the encoder and decoder example.

### ISSUE THREAD

**Issue by Torkoal** [Element-Research/rnn#68]
Hello! I just found this library and have been trying to use seq2seq learning to flip a sequences of numbers. However, i'm stuck trying to understand how each of these tensors in the encoder decoder example...

    encInSeq
    decInSeq
    decOutSeq

...each relate to a seq2seq model like this:
![Image of Model]
(http://i.imgur.com/MBqqaqH.png)
My current understanding is that `encInSeq` is the tensor input that is given to the encoder network, the `decInSeq` is the tensor input given to the decode network, and finally decOutSeq is the expected output tensor for the decode layer. Is this correct? The fact that all of these tensors are 2x3 and 2x4 doesn't seem to match with this understanding. I'm sorry if this question seems obvious, but I have trying to figure this out for a few days now. (I'm new to using Torch for RNNs.) Thanks!

**Comment by douwekiela** [comment]
In your example picture, `encInSeq = ABC`, `decInSeq = <EOS>WXYZ` and `decOutSeq = WXYZ<EOS>`. The example is mini-batched, in this case with a batch size of 2 - so we have two training examples. The encoded input sequence can be of a different length from the decoded sequence (which have to be of the same length). Does that help?

**Comment by Torkoal** [comment]
Yes it does! Thank you so much for your help! It seem obvious now.

**Comment by htw2012** [comment]
local encInSeq = torch.Tensor({{1,2,3},{3,2,1}})
local decInSeq = torch.Tensor({{1,2,3,4},{4,3,2,1}})
local decOutSeq = torch.Tensor({{2,3,4,1},{1,2,4,3}})
 I think your data decInSeq and decOutSeq is not  match? @douwekiela

**Comment by douwekiela** [comment]
@htw2012: The example does not use real data, mostly because I did not want to get into trouble with padding and masking. If you want to improve it, feel free to submit a PR.
