### ISSUE TITLE
Dropout "sizes do not match" error on backward pass

### ISSUE THREAD

**Issue by senecaur** [Element-Research/rnn#72]
I am trying to train a stacked LSTM by calling forward/backward one step at a time.  I need to do this because I run out of memory if I use a Sequencer on the whole mini-batch of sequences.  If I just run the forward pass all is well; but when I add in the backward pass I get the error:

 ```...Dropout.lua:42: bad argument #2 to 'cmul' (sizes do not match at /home/ubuntu/torch/extra/cutorch/lib/THC/THCTensorMathPointwise.cu:132)```

Here is a code snippet for my model and feval function (I am using Optim for training):

```
model = nn.Sequential()
model:add(nn.LookupTable(vocab_size, 512))
model:add(nn.FastLSTM(512, opt.rnn_size, opt.seq_length))
model:add(nn.Dropout(opt.dropout))
model:add(nn.FastLSTM(opt.rnn_size, opt.rnn_size, opt.seq_length))
model:add(nn.Dropout(opt.dropout))
model:add(nn.FastLSTM(opt.rnn_size, opt.rnn_size, opt.seq_length))
model:add(nn.Dropout(opt.dropout))
model:add(nn.Linear(opt.rnn_size, vocab_size))
model:add(nn.LogSoftMax())
criterion = nn.ClassNLLCriterion()
model:cuda()
criterion:cuda()

x, dl_dx = model:getParameters()

function feval(x_new)
    if x ~= x_new then
        x:copy(x_new)
    end

    ------------------ get minibatch -------------------
    local inputs, targets = loader:next_batch(1)
    ------------------- forward pass -------------------
    dl_dx:zero()

    local loss_x = 0

    outputs = {}

    for i = 1,opt.seq_length do
        local lst = model:forward(inputs[i])
        table.insert(outputs, lst)
        loss_x = loss_x + criterion:forward(lst, targets[i])
    end

    loss_x = loss_x / opt.seq_length

    for i = opt.seq_length,1,-1 do
        model:backward(inputs[i], criterion:backward(outputs[i], targets[i]))
    end

    dl_dx = torch.clamp(dl_dx,-opt.grad_clip,opt.grad_clip)

    return loss_x, dl_dx
end
```

**Comment by hughperkins** [comment]
(just on the off-chance, is it an off-by-one error?  because I'm just thinking that presumably the targets are probably the inputs, delayed by 1?  And so, for the very last input, is the target somehow missing?)

**Comment by senecaur** [comment]
Doesn't seem to be the problem.  Both "inputs" and "targets" have the same size when I inspect them at run-time.  They are both tables 100 length tables where each entry is a length 128 1D cuda tensor.

**Comment by senecaur** [comment]
I should note, that if I do use a Sequencer around the model and just make my batch size very small then the network does train correctly.  So the problem is related to my looping over the sequence manually.

**Comment by hughperkins** [comment]
should each target be the class label, ie a single number, rather than a one-hot one-of-k vector?

**Comment by senecaur** [comment]
That's what I currently have.  Each of the cuda tensors in the targets table contains a batch of 128 class labels.  This is what's required by the ClassNLLCriterion.  Should I be using one-hot vectors for the target  other than for evaluating the criterion?

**Comment by hughperkins** [comment]
I think target should be the label, and the input should be one-hot. (this is not my repo by the way, I'm just a bystander).  So, if your input and your target are the same dimension, does that mean your input is not in fact one-hot?

**Comment by senecaur** [comment]
Thanks for your help!

My input is not one-hot, but it does go through an nn.LookupTable layer at the beginning of the model to turn it in to an embedding.  I thought that might be part of the problem, but then I don't see why the error would appear in one of the dropout layers.

**Comment by hughperkins** [comment]
> but then I don't see why the error would appear in one of the dropout layers.

My idea was that in the forward pass, it's setting the dimensions of the input to the dropout layer, which is used to generate the dropout mask.  Then in the backward pass, the dropout mask is used to guide the gradients backwards, via the cmul.  And I was thinking that maybe the size of the dropout mask doesnt match the size of the backwards-flowing gradients.

**Comment by nicholas-leonard** [comment]
@senecaur Add `model:backwardOnline()` before calling your feval.

**Comment by senecaur** [comment]
That fixed it - thanks!  Feel free to close the issue.

It now runs out of memory too though. I thought that might be the case...

**Comment by nicholas-leonard** [comment]
@senecaur What is your seq_length?

**Comment by senecaur** [comment]
100.  I'm trying to use a batch size of 128.  I have an implementation in Chainer that is able to do this in ~6GB of GPU memory.  Are there any ways I can improve memory efficiency here?  Thanks

**Comment by nicholas-leonard** [comment]
so you have 1 sample per batch (batchSize) and 128 steps per sequence (sequence length, i.e. rho). If you want to reduce the memory footprint, you will need to reduce your sequence length. The LSTM has lots of intermediate steps for which it must maintain a gradInput and output tensor internally, for each step. So yeah, not surprising that this takes a lot of memory.

Your Chainer implementation might be using some inplace memory tricks which Torch doesn't support that well. Right now, inplace activations are only supported for ReLU, which doesn't make up a significant portion of your network.

**Comment by senecaur** [comment]
No, I have 128 samples per step and 100 steps per sequence.  If I understand correctly this means that rho should be 100?

**Comment by nicholas-leonard** [comment]
Yeah. So just reduce 128.

**Comment by senecaur** [comment]
Yep, that works.  I have to reduce it ~32 to stay within memory, but then training is ~4X slower than the Chainer implementation.
