### ISSUE TITLE
Question: does this package work with optim? (yes)

### ISSUE THREAD

**Issue by kmnns** [Element-Research/rnn#77]
Thank you for this awesome package. Much wow.

I cannot use *dp* which all examples are based on (https://github.com/Element-Research/rnn/issues/60).
So I have to make sure *optim* is supported for architectures like these:

```
Sequencer( 
  Sequential( 
    module1, 
    LSTM,
    module2, 
    ...
  ) 
)
```

```
Sequential( 
  module1, 
  Sequencer( 
    LSTM 
  ), 
  module2, 
  ... 
)
```

The second one was suggested for a many-to-one transducer in https://github.com/Element-Research/rnn/issues/21.

*AbstractRecurrent* says that BPTT happens in `updateParameters()` (https://github.com/Element-Research/rnn/blob/master/AbstractRecurrent.lua#L87). But *optim* manipulates the parameters directly, never calls `updateParameters()`.

UPDATE: Sorry, a little confused about how similar stuff happens in different places.
Apparently, as long as you decorate with the *Sequencer* container, *optim* should work fine.

*optim* just wants you to call `backward()` on your net and provide the *gradParams*. `backward()` on your *Sequencer* should handle all the BPTT:

```
Module:backward() -> 
    Sequencer:updateGradInput() -> BPTT( LSTM:updateGradInput() )
    Sequencer:accGradParameters() -> BPTT( LSTM:accGradParameters() )
```

If someone with a bit more insight could verify this, I would be super happy. Thanks!

Going to close this issue then.

**Comment by nicholas-leonard** [comment]
@kmnns Yup you got it.
