### ISSUE TITLE
Nested Sequencer

### ISSUE THREAD

**Issue by angelifrangite** [Element-Research/rnn#78]
Hey guys,

I am currently writing and testing some minimalexamples of this repo.
I have one problem with understanding the way I should handle sequencer in models, e.g. nested sequencer. 

Can anybody tell me how I get the inner LSTMs to work?

``` lua
require 'nn'
require 'rnn'

local inputsize = 10
local outputsize = 12

local inputdata_t = torch.rand(10)

local innermodel = 
nn.Sequencer(
 nn.Sequential()
  :add(FastLSTM(inputsize, 2))
  :add(FastLSTM(2, 5))
)

local model = 
nn.Sequential()
  :add(nn.CAddTable())
  :add(innermodel)
  :add(nn.Linear(5,12))

model =  nn.Recurrence(model, 12, 1)

local inputs = {}
for ii=1,3 do
 table.insert(inputs, inputdata_t[ii])
end

local outputs = model:forward(inputs)

```

I guess I need to wrap the complete module in another Sequencer? But how do I take different rhos for different modules in the same model.

Is there some kind of hold unit which catches the outputs?

Thx for helping

**Comment by kmnns** [comment]
`Sequencer` wants to be wrapped in in some table processing. Meaning:

- input: table of tensors (one per time step)
- output: table of tensors (one per time step, or whatever you want)

[This example](https://github.com/Element-Research/rnn#decorate-it-with-a-sequencer) shows how a fully `Sequencer`-wrapped network is fed a table of tensors.

You can also wrap just a part of the network with a `Sequencer`, but make sure there are table layers around it.

For example, this deep beauty (many-to-one transducer with nngraph) works for me: 

```lua
local lstm_stack = nn.Sequential()
    :add(nn.LSTM(loader.vocab_size, opt.hidden))
    :add(nn.LSTM(opt.hidden, opt.hidden))

local split     = nn.SplitTable(1)()
local recurrent = nn.Sequencer(lstm_stack)(split)
local last      = nn.SelectTable(-1)(recurrent)
local linear    = nn.Linear(opt.hidden, opt.n_classes)(last)
local soft      = nn.LogSoftMax()(linear)

local net = nn.gModule({split}, {soft})
```

**Comment by angelifrangite** [comment]
Hey thank you for your answer. The whole manipulation with the sequencer is really hard to understand (at least for me). I think I get your idea about table processing...

After spending the last two days trying to understand every step in the process I think I found the problem.
My current solution for my problem is this model design:
``` lua
inputsize = 10
outputsize = inputsize_

innermodel =
nn.Recursor(
 nn.Sequential()
  :add(nn.FastLSTM(inputsize, 5))
)

model =
nn.Sequencer(
 nn.Sequential()
  :add(nn.CAddTable())
  :add(innermodel)
  :add(nn.Linear(5,outputsize_))
  :add(nn.Sigmoid())
)
```
The innermodel wouldn't work without the Recursor. I think I get the reason why. If I am implementing a Linear module in the innerlmodel, I don't need a Recursor.
but to be honest I am not sure if this is a) right b) efficient and c) does what it is supposed to do.

But at least it is calculating. I try to validate the results but I am not sure atm how I should do it.

Can anybody see if my model false design-wise?

Thanks for helping!

**Comment by kmnns** [comment]
Yes it is a bit tricky, but the table-interface makes sense. The robustness in this library comes with some seeming functional redundancy here and there, which is why trying to track method calls between this library and `nn` can be quite confusing.

According to [this](https://github.com/Element-Research/rnn#decorate-it-with-a-sequencer), Recursor and Sequential are not needed here for the hidden layer.

I think bare LSTM can only be used with a manual (i.e. "online") backprop, but don't me accountable.

(btw: I think FastLSTM doesn't use peepholes, beware.)

**Comment by angelifrangite** [comment]
Oh I see, I forget some modules while copying from my real net.

This is why I had to (imho) use them, sorry for the confusion!

``` lua
inputsize = 10
outputsize = inputsize
outputsize_ = 12

innermodel = 
            nn.Recursor(
                nn.Sequential()
                :add(nn.Linear(inputsize, 20))
                :add(nn.FastLSTM(20, outputsize_, opt.rho))
            , opt.rho)
    
model = 
        nn.Sequential()
        :add(nn.CAddTable())
        :add(innermodel)
        :add(nn.Linear(outputsize_,outputsize))
        :add(nn.Sigmoid())    
 
        
    return nn.Sequencer(
                nn.Recurrence(model, outputsize, 1)
            )
```

I edited it in my other posting to avoid confusion in the future!

**Comment by kmnns** [comment]
Doesn't this explode with errors? Recursor without surrounding Sequencer?

> Recursor: This module decorates a module to be used within an AbstractSequencer instance.

And I think Recurrence is only for making your own recurrent modules, not to be wrapped into a Sequencer. But if it runs it runs.

I would have tried something along the lines of

```lua
innermodel = 
            nn.Sequencer(
                nn.Sequential()
                :add(nn.Linear(inputsize, 20))
                :add(nn.FastLSTM(20, outputsize_, opt.rho))
            )

model = nn.Sequential()
        :add(nn.CAddTable())
        :add(innermodel)
        :add(nn.Linear(outputsize_,outputsize))
        :add(nn.Sigmoid())   
```

Sequencer wraps non-AbstractRecurrent modules automatically in a Recursor.

I am not sure what you want to do with this, so just pure guess-work.

**Comment by angelifrangite** [comment]
I think you're right about the Recurrence. But I used a selfwritten module that did pretty much exactly the same (took the output and made it to an additional input of the next step).
But this one is - in contrast to my version - good implemented, written in a consistent style and tested by someone who understands what he is talking about.

So I try to implement in my net (and the minimal examples I am collecting/writing.

It calculates at the moment and the first results look promising, so I _think_ it should work as I hoped.

But I would be happy if anyone could tell me if I make a mistake and the results just happen to look good without a functional net - I am very new to the ml so I have no intuition about nothing here...

**Comment by nicholas-leonard** [comment]
@angelifrangite Is this what you want to do? 

```lua
require 'rnn'

batchsize = 4 -- number of samples per batch
inputsize = 10
outputsize = inputsize
outputsize_ = 12
rho = 10 -- sequence length

recurrentModule = nn.Sequential()
   :add(nn.Linear(inputsize, 20))
   :add(nn.FastLSTM(20, outputsize_, rho))
   :add(nn.Linear(outputsize_,outputsize))
   :add(nn.Sigmoid())    


model = nn.Sequencer(recurrentModule)

input = {}
for i=1,rho do
   table.insert(input, i, torch.randn(batchsize, inputsize))
end

output = model:forward(input)
print(output)
```

output is :

```lua
{
  1 : DoubleTensor - size: 4x10
  2 : DoubleTensor - size: 4x10
  3 : DoubleTensor - size: 4x10
  4 : DoubleTensor - size: 4x10
  5 : DoubleTensor - size: 4x10
  6 : DoubleTensor - size: 4x10
  7 : DoubleTensor - size: 4x10
  8 : DoubleTensor - size: 4x10
  9 : DoubleTensor - size: 4x10
  10 : DoubleTensor - size: 4x10
}
```

**Comment by angelifrangite** [comment]
No, not really.
I tried to draw the topology:
[net.pdf](https://github.com/Element-Research/rnn/files/61852/net.pdf)

My atm calculating code is (minimized):

``` lua
require 'torch'
require 'nn'
require 'rnn'

torch.manualSeed(123)
rho = 4
inputsize = 10
outputsize = inputsize

function defineModel()
  local innermodel = 
            nn.Recursor(
                nn.Sequential()
                :add(nn.FastLSTM(inputsize, inputsize, rho))
                :add(nn.FastLSTM(inputsize, inputsize, rho))
            , rho)
    
    local model = 
        nn.Sequential()
        :add(nn.CAddTable())
        :add(innermodel)
        :add(nn.Linear(inputsize,outputsize))
        :add(nn.Sigmoid())    
 
        
    return nn.Sequencer(
                nn.Recurrence(model, outputsize, 1)
            )
end

model = defineModel()

inputs = {}
for step=1, rho do
 table.insert(inputs, torch.ones(10))
end

outputs = model:forward(inputs) 

print(outputs)
```

But now, as I look at it, I could have just used:

``` lua
require 'torch'
require 'nn'
require 'rnn'

torch.manualSeed(123)
rho = 4
inputsize = 10
outputsize = inputsize

function defineModel()
  local innermodel = nn.Sequential()
                :add(nn.FastLSTM(inputsize, inputsize, rho))
                :add(nn.FastLSTM(inputsize, inputsize, rho))
                
    local model = 
        nn.Sequential()
        :add(nn.CAddTable())
        :add(innermodel)
        :add(nn.Linear(inputsize,outputsize))
        :add(nn.Sigmoid())    
 
        
    return nn.Sequencer(
                nn.Recurrence(model, outputsize, 1)
            )
end

model = defineModel()

inputs = {}
for step=1, rho do
 table.insert(inputs, torch.ones(10))
end

outputs = model:forward(inputs) 

```
with the exact same results. So I guess I didn't break my model, but I just made it more complicated and misused the recursor (although it works ôO).


But one question remains:
Is/was it wrong to use Recurrence to directly feed the output back into my model? In my mind I need it, because it is the only way I can think of where I can init my net with my desired output.

For this I use:
```lua
model:get(1):get(1).userPrevOutput = mydesiredOutputTensor
```

Sorry for bringing so much confusion here. I thought I'd understood it. Back to reading source code and trying to get the concepts I guess...

Thanks everybody for helping!

**Comment by nicholas-leonard** [comment]
@angelifrangite I think your second example in the previous post is the most accurate. But like you, I think your first example in the previous post would also work, although it does overcomplicate it.

To answer your question, your use of the recurrence seems valid here as this is the best way to feed back `output[t-1]` along side `input[t]`. And it is the only solution if you need `userPrevOutput`. So yeah, you got it right, you understand it. No need to dive back into the source code, I think?

**Comment by angelifrangite** [comment]
Thanks everybody for helping and correcting!
