### ISSUE TITLE
GRU init problem

### ISSUE THREAD

**Issue by rracinskij** [Element-Research/rnn#79]
Hi,
probably a dumb issue, but still can't figure it out - 
trying to init a GRU (e.g., r = nn.GRU(1,1)) gives an 'attempt to call field 'GRU' (a nil value)' error.

Same code for LSTM works fine. Would appreciate any help.

**Comment by jnhwkim** [comment]
did you update the package using 
    luarocks install rnn
?

**Comment by rracinskij** [comment]
Thanks a lot, didn't notice it.
