### ISSUE TITLE
Question about input/output dimensions

### ISSUE THREAD

**Issue by cjmcmurtrie** [Element-Research/rnn#81]
I'm going through the documentation for the library and there's something basic I'm not understanding about the input to rnn.LSTM and rnn.GRU.

In the documentation, following the method description for backwardOnline([online]), this dummy data is generated for the example:

> -- generate some dummy inputs and gradOutputs sequences
inputs, gradOutputs = {}, {}
for step=1,5 do
   inputs[step] = torch.randn(3,10)
   gradOutputs[step] = torch.randn(3,10)
end

Which feeds into the following module:

> -- an AbstractRecurrent instance
rnn = nn.LSTM(10,10)

My interpretation was that this was inputing sequences of 3 vectors, each vector having 10 features. However, this doesn't make sense in the context of the document, because of the code that follows:

> for step=1,5 do
   rnn:forward(inputs[step])
   rnn:backward(inputs[step], gradOutputs[step])
end
rnn:backwardThroughTime()
rnn:updateParameters(0.1)
rnn:forget()

forget() should be called at the end of a single sequence, in my understanding. So rather, what seems to be happening is we are inputting a sequence of 5 tensors of dimension 3x10.

However, this goes against my interpretation of an LSTM, which in all my previous experience should take as input a sequence of vectors, not a sequence of matrices (tensors). I have no understanding of how an LSTM or any RNN would take a sequence of two dimensional tensors, rather than vectors.

I would greatly appreciate a clarification of my misunderstanding here.

Thanks!

**Comment by nicholas-leonard** [comment]
@cjmcmurtrie Yeah so the confusion stems from the fact that it may not be obvious that each of the 3 rows are independent samples of a batch of 3 samples. So the first row of each tensor form the first sequence : 
```lua
seq1 = {inputs[1][1], inputs[2][1], inputs[2][1],...}
```
The second sequence is found in the second rows : 
```lua
seq2 = {inputs[1][2], inputs[2][2], inputs[2][2],...}
```
And so forth and so on. This is counter-intuitive because you expect each element of the table to be its own sequence. But each element of the sequence needs to be fed to the GPU one time-step at a time, so we optimize this by batching elements into a tensor to be fed to GPU in one call every time-step.

**Comment by cwellsarnold** [comment]
Just for clarity, I think you meant that the third elements in each row should have an index of 3 in their first dimension, i.e.,  `inputs[3][1]` and `inputs[3][2]`?

**Comment by cjmcmurtrie** [comment]
Nicholas, thank you for clarifying this, it makes sense now.

This kind of batching seems unusual to me. What I have seen in the past is creating a (item x words x features) tensor. I wonder if there would be speed gains in doing it slightly differently. However this is very helpful, thank you - and I love the library!

**Comment by nicholas-leonard** [comment]
@cwellsarnold The first dimension `inputs[i]` (here indexed by i) indexes the elements of the table, i.e. the steps in the sequence. The second dimension `inputs[i][j]` (here indexed by j) indexes the rows of the tensor (at step i), i.e. the j-th sample in the batch.

@cjmcmurtrie IMHO, there probably wouldn't be much of a speed gain. And it wouldn't be too difficult to modify Sequencer to accept tensors AND tables thereof.
