### ISSUE TITLE
A question about converting the inputs 

### ISSUE THREAD

**Issue by ayanamongol** [Element-Research/rnn#83]
Thanks for the library first.

My question is, I have a input data which is 

[torch.LongTensor of size 30x100]

and I want to convert it into a Table consists of 30 sub-tables, 
and each sub-table has 100 sub-sub tables  : DoubleTensor of Size 1

Then I can put them into a LSTM

is it possible to be implemented using modules like nn.SplitTables(1) ?

I tried:

mlp = nn.Sequential()
mlp:add(nn.SplitTable(1))
mlp:add(nn.Sequencer(nn.SplitTable(1)))

But What i got is not DoubleTensor of Size 1. What can i do?

**Comment by nicholas-leonard** [comment]
@ayanamongol 

Try adding a dimension : 
```lua
require 'rnn'

input = torch.LongTensor(30,100)

mlp = nn.Sequential()
mlp:add(nn.View(30,100,1))
mlp:add(nn.SplitTable(1))
mlp:add(nn.Sequencer(nn.SplitTable(1)))

print(mlp:forward(input))
```

**Comment by ayanamongol** [comment]
Thanks very much for the quick reply, but its still LongTensors and they can not be put into a nn.LSTM, right?
