### ISSUE TITLE
For info, creating port of char-rnn to element-research rnn

### ISSUE THREAD

**Issue by hughperkins** [Element-Research/rnn#96]
For info, creating port of char-rnn to element-research rnn

https://github.com/hughperkins/char-rnn-er

It's draft for now.  If you can think of a better name, please go ahead and suggest.  I suck at names :-)

I decided to make a separate repo for it, rather than putting in examples here, because it takes up multiple files, a bit too big for a simple example scriptfile really.

**Comment by nicholas-leonard** [comment]
@hughperkins Let me know if you need help. When ready, I will add link to that repo's README from rnn README. Name is functional, users searching google for `char-rnn` should see your repo (when google indexes it).
