### ISSUE TITLE
cuda support

### ISSUE THREAD

**Issue by lifengjin** [Element-Research/rnn#97]
I saw some usage of gpu in the examples, but it was used with the dp package. Is it possible to make any arbituary sequencer run on gpus?
Thanks,
Lifeng

**Comment by jnhwkim** [comment]
@lifengjin Probably, yes. Can you elaborate your situation?

**Comment by nicholas-leonard** [comment]
@lifengjin To make it run using CUDA, cast module and criterion to cuda : 
```lua
module:cuda()
criterion:cuda()
```

You will also need to make sure your `input, target` tensors have the right type (probably `torch.CudaTensor`)

**Comment by lifengjin** [comment]
I want to build a LSTM on top of a BiLSTM where the output of the BiLSTM is concatenated with other vectors from Identity to form the input of the LSTM. There does not seem to be an easy way to do this with parallel and join table, but that's a different issue. Say I have 
`<bilstm>`
`<join = whatever function to combine the output of bilstm and other vectors>`
`<lstm>`
Do I just do `<:cuda>` to all the models?

**Comment by nicholas-leonard** [comment]
@lifengjin Yes. So you would have something like : 
```lua
-- build model
model = nn.Sequential():add(blstm):add(nn.JoinTable()):add(lstm)
-- cast to cuda
model:cuda()
```
